### ISSUE TITLE
[BUG] Remove memory leaks from soa_readers.pyx and trajectory.pyx

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#101]
Temporary `gdf_columns*` allocated are never freed in the named files.

**Comment by taureandyernv** [comment]
Hey @thomcom , may we close as although you may have fixed the issue, it seems that the files in question had been removed by 0.14 release?  Thanks bud!

**Comment by thomcom** [comment]
Yup, thank you @taureandyernv !
