### ISSUE TITLE
[FEA]: Refactor binpred architecture for better extensibility

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#1012]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

The binpred architecture used for the contains and equals predicates needs an overhaul. I'll be updating it to extend to all feature combinations for this issue.

Closed by #1009

**Comment by harrism** [comment]
Is this going in the design document to specify requirements and reasons for the "overhaul"?

**Comment by thomcom** [comment]
Yeah I'll update the design document with the new design decisions and explanation. The docs in the PR are quite thorough.
