### ISSUE TITLE
[FEA]: Need a libcuspatial `count_equal_points(lhs, rhs)` function.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#1020]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

As I've been implementing binary predicates I've discovered that there are plentiful cases wherein I need the ability to count the number of points in one buffer that are equal to the number of points in another buffer. While numerous equality comparisons are possible and fast in python, I can't without iteration compare a series of points, pairwise,with all other points in a buffer for equality.

For example,
```
mp1 = [0, 1, 3, 2, 4, 5, 7, 6]
mp2 = [0, 1, 2, 3, 4, 5, 6, 7, 4, 5]
result = count_equal_points(mp1, mp2)
print(result)
1
0
2
0
```

This feature is useful for many binary predicates, and can't be trivially implemented in python.

**Comment by isVoid** [comment]
Not sure if I understand the input.

> ```
> x = [0, 1, 3, 2, 4, 5, 7, 6]
> y = [0, 1, 2, 3, 4, 5, 6, 7, 4, 5]
> result = count_equal_points(x, y)
> print(result)
> 1
> 0
> 2
> 0
> ```

- `x` and `y` doesn't have the same number of input. Is this x/y coordinate?
- Can you explain what does 1 0 2 0 stand for?

**Comment by thomcom** [comment]
The output is an allpairs count equals result:
1 = x[0:2] == y[0:2]
0 = x[2:4] != any in y
2 = x[4:6] == y[4:6] and y[8:10]
0 = x[7:8] != any in y

One implementation pseudocode might be:

    for each even number in len(x) as i:
        for each even number in len(y) as j:
            if x[i] == y[i] and x[i+1] == y[i+1]:
                result[i]++

**Comment by thomcom** [comment]
These are interleaved xy buffers.

**Comment by isVoid** [comment]
So this looks like an all pairs equals count for two point arrays, or two multipoints. Do you just need this for single point array or multipoint array as well?

**Comment by thomcom** [comment]
I only need it for single point array, I can convert any other geometry type into that as needed.

**Comment by harrism** [comment]
So the X and y arrays are not x- and y-coordinates? Can you make the original request example less confusing by not naming them X and y?

**Comment by harrism** [comment]
Do you want the count of matches of each point in the LHS to points of the RHS? Or do you just want true/false if each point in the LHS exists in the RHS? Two different algorithms with different costs...

**Comment by isVoid** [comment]
> mp1.touches(mp2), where I only need to know if any point in mp1 is equal to any point in mp2.

For this I think you only need a `True` and `False` test? You don't need to create a counting function.

**Comment by harrism** [comment]
I would think Thrust set operations would be useful for these.
