### ISSUE TITLE
[BUG]: Segment Iterator is flawed, may fail if input contains 0-length geometry

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#1055]
### Version

23.04

### Describe the issue

Currently, `multilinestring_range::segment_begin()` require that the input doesn't include empty geometries. Such as:

```
geometry offset: 0, 1, 2
part offset: 0, 0, 2
Coords: (0, 0) (1, 1)
```

A complete solution require counting the number of skipped geometries prior to current linestring, and it would require tracking the result in an owning object, which is not what *_range designed to do.

**Comment by harrism** [comment]
More info: I suggested an efficient algorithmic solution to this problem, and paired with Michael on implementation, however we ran up against the need for an owning data structure and decided to wait to implement it until after support for non-0-length geometry is finished.
