### ISSUE TITLE
Might Need Real .Contains

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#1071]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

We might need to modify the line-crossings algorithms to work like `.contains`, that is, that a point located on the boundary of a polygon is computed to be contained by that polygon.

I'm working with basic predicates here, equals, pip (`contains_properly`), and intersection, and I've found a test case that I don't think I can solve:

```
  x
--|--
| | |
| | |
| | |
--|---
  x
```
and
```
--x--
| | |
| | |
| | |
--x--
```
Are indistinguishable, so I need boundary-inclusive `.contains` by modifying the line-crossings algorithms.

### Describe any alternatives you have considered

I'm currently investigating an approach by dividing up the linestring into points, and testing each point separately for intersection. If a linestring is not contained but it does have point intersections, it is `contain`ed. Opening this for consideration and discussion, can you think of another way

**Comment by isVoid** [comment]
How about an extra parameter for Point-in-Polygon kernel that allow runtime configuration of boundary exclusion/inclusion?

**Comment by thomcom** [comment]
That works for me.

**Comment by thomcom** [comment]
Another option has to do with the intersection API.
Currently this configuration returns a pair of linestrings:
```
-----
|   |
x-x |
| | |
x-x--
```
It is a smaller polygon intersecting with a larger polygon, with two shared edges. If this returned in some way the 3 points that are all "in" the intersection, I could probably implement `.contains` as it is in the design doc, with `count_pip(a,b) + count_intersects(a,b) == 4`.

**Comment by harrism** [comment]
>  I've found a test case that I don't think I can solve:

Test case for which relationship? Please be precise. Are you trying to determine if the linestring and the polygon intersect, overlap, contain, or what?
