### ISSUE TITLE
[FEA] Build conda environment file

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#11]
**Is your feature request related to a problem? Please describe.**
It should be possible to use cuspatial as a standalone library. One of the easiest ways of doing this is to create a conda environment file that makes installing all of the dependencies easy.

**Describe the solution you'd like**
Let's build a conda environment for cuspatial.

**Comment by taureandyernv** [comment]
Hey @thomcom , I think we can close this FR.  This seems to have been one and @Salonijain27 updated it in PR #303 .  Thanks man!

**Comment by thomcom** [comment]
done thannks @taureandyernv
