### ISSUE TITLE
[BUG]: `linestring_polygon_distance_test.cpp` is out of place

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#1105]
### Version

23.06

### On which installation method(s) does this occur?

Rapids-Compose

### Describe the issue

`linestring_polygon_distance_test.cpp` is out of place after libcuspatial file re-organization. I made a mistake when merging https://github.com/rapidsai/cuspatial/pull/1030

**Comment by harrism** [comment]
I think I fixed this in my still open PR? Can you check? If so, no need for a separate PR.

**Comment by isVoid** [comment]
I don't think so? `There's cpp/tests/spatial/distance/linestring_polygon_distance_test.cu` under `tests/spatial/distance/` in that PR. But there isn't `cpp/tests/spatial/distance/linestring_polygon_distance_test.cpp`.

**Comment by harrism** [comment]
OK, I just moved it in that PR. I'd rather avoid the conflicts.
