### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'cuspatial._lib.spatial'

### ISSUE THREAD

**Issue by rsignell-usgs** [rapidsai/cuspatial#112]
**Describe the bug**

 ```
import cuspatial
```
results in
```
ModuleNotFoundError: No module named 'cuspatial._lib.spatial'
```

**Environment details**

* We are running on AWS on a `g3s.xlarge`. 

* We used this [environment.yml](https://github.com/scottyhq/jupyter-cupy/blob/master/binder/environment.yml) to build the container for JupyterHub.

**Comment by thomcom** [comment]
I'm not sure why you're seeing this, looking into it.

**Comment by taureandyernv** [comment]
Hey @rsignell-usgs, in the spirit of helpfully documenting for others who face similar issues, please know that you are not running a GPU enabled system.  Please use a g4dn, p3, or p4 instance to run RAPIDS it should would.  I regret the delay in getting back to you with a solution.

@thomcom , please close this issue.  Thanks man!

**Comment by thomcom** [comment]
Thanks @taureandyernv
