### ISSUE TITLE
[DOC] How to run  point_in_polygon 

### ISSUE THREAD

**Issue by linwoodc3** [rapidsai/cuspatial#115]
**What is your question?**

Is it possible for someone to create a simple notebook example on how to run a point in polygon test with cuSpatial?

In looking at the demos folder for several hours, I'm not seeing how to get from this:

```
import shapely,shapefile
from shapely.geometry import Polygon
plyreader = shapefile.Reader('/content/drive/My Drive/osm_stuff/osm_us_landuse.shp')
polygon = plyreader.shapes()
plys = []
for shape in polygon:
    plys.append(Polygon(shape.points))

```

To the code where I pass something into the `cuspatial.point_in_polygon_bitmap` function.  

For background, I'm coming from `geopandas` and a heavy `pandas` background. The convenstions and code I'm seeing in cuSpatial are different and I'd like to get some help on understanding how to use the library.  It seems powerful from the description, but I'm looking for an example that is straightforward.  Thanks in advance for the help.

If possible, can someone's example use a real shapefile like the demo examples?  However, the demo scripts in cuSpatial read in the file but I never saw a use of testing for point in polygon.  

So, to be clear, I'm asking if someone can make a simple example of loading a shapefile, loading points, and testing if points are inside the polygons that come from the shapefile.

**Comment by linwoodc3** [comment]
The main problem is this as well, when I try to read a shapefile, I get this:

```
shapes = cuspatial.read_polygon_shapefile('/content/drive/My Drive/osm_stuff/osm_landuse.shp')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-bd413586442e> in <module>()
----> 1 shapes = cuspatial.read_polygon_shapefile('/content/drive/My Drive/osm_stuff/osm_us_landuse.shp')

4 frames
/usr/local/lib/python3.6/site-packages/cuspatial/io/shapefile.py in read_polygon_shapefile(filename)
     10     result = cpp_read_polygon_shapefile(filename)
     11     return (
---> 12         DataFrame({"f_pos": result[0], "r_pos": result[1]}),
     13         DataFrame({"x": result[2], "y": result[3]}),
     14     )

/usr/local/lib/python3.6/site-packages/cudf/core/dataframe.py in __init__(self, data, index, columns, dtype)
    183 
    184             for i, (col_name, series) in enumerate(data):
--> 185                 self.insert(i, col_name, series, forceindex=index is not None)
    186 
    187         self._add_empty_columns(columns, index)

/usr/local/lib/python3.6/site-packages/cudf/core/dataframe.py in insert(self, loc, column, value, forceindex)
   1557             )
   1558         self._cols[column] = self._prepare_series_for_add(
-> 1559             value, forceindex=forceindex, name=column
   1560         )
   1561         keys = list(self._cols.keys())

/usr/local/lib/python3.6/site-packages/cudf/core/dataframe.py in _prepare_series_for_add(self, col, forceindex, name)
   1518         series = Series(col, name=name) if not SCALAR else col
   1519         self._sanitize_columns(series)
-> 1520         series = self._sanitize_values(series, SCALAR)
   1521 
   1522         empty_index = len(self._index) == 0

/usr/local/lib/python3.6/site-packages/cudf/core/dataframe.py in _sanitize_values(self, series, SCALAR)
   1496                 return Series(arr)
   1497         elif len(self) > 0 and len(sind) != len(index):
-> 1498             raise ValueError("Length of values does not match index length")
   1499         return series
   1500 

ValueError: Length of values does not match index length
```

**Comment by linwoodc3** [comment]
And I'll add, I want to help by contributing (maybe documentaion, examples).  But right now, I can't follow how to use the library.  Just need a good example to get started.

**Comment by zhangjianting** [comment]
@linwoodc3 
Sorry for lacking detailed documentation which was long overdue. 
A good way to learn PIP in cuSpatial is its unit test code at https://github.com/rapidsai/cuspatial/blob/branch-0.12/python/cuspatial/cuspatial/tests/test_pip.py
An old demo that compare Shapely and cuSpatial PIP is provided at https://github.com/rapidsai/cuspatial/blob/branch-0.12/python/cuspatial/demos/pip_verify_shapely_locust.py
However, the demo reads point and polygon data from cuSpatial's internal binary representation. I will develop a new demo to read polygon data using cuSpatial's new ShapefileReader API.

**Comment by zhangjianting** [comment]
@linwoodc3 @thomcom There is an issue in cuspatial/io/shapefile.py. 
f_pos records the ending positions of rings of polygons in an ring index array, whose values are the prefix-sum of numbers of the rings of polygons. If all polygons have a single ring, f_pos have values of 1,2, 3 and so on. If the second polygons have two rings instead, then the values would be 1,3, 4 and so on. 
Similarly, r_pos records the ending positions of vertices of rings. If there are three rings in total and each ring has 5,6 and 4 rings, then r_pos would have values of 5,11 and 15. Note that the first and the last vertex of a ring must have a same value. As such, a triangle would have 4 vertices.  When read from a shapefile or from a preprocessed SOA binary file, f_pos, r_pos and x/y are automatically filled.  

As such,  f_pos(result[0]) and r_pos(result[1]) will have different lengths and can not be put together into a DataFrame. 
A workaround is to call cpp_read_polygon_shapefile directly, as shown in the following example.  I can share the .py file with you through email or slack. 

#make sure your CUSPATIAL_HOME is set 

import os
from cuspatial._lib.shapefile_reader import cpp_read_polygon_shapefile
from cuspatial.core.gis import point_in_polygon_bitmap

sp_path=os.path.join(os.environ['CUSPATIAL_HOME'],'test_fixtures/shapefiles','two_polys.shp')
print(sp_path)
result=cpp_read_polygon_shapefile(sp_path)

f_pos = cudf.Series(result[0])
print(f_pos.astype('int32'))
r_pos = cudf.Series(result[1])
print(r_pos.astype('int32'))
ply_x= cudf.Series(result[2])
print(ply_x.astype('float64'))
ply_y= cudf.Series(result[3])
print(ply_y.astype('float64'))

pnt_x=cudf.Series([0, -8, 6.0]) # x coordinates of 3 query points
pnt_y=cudf.Series([0, -8, 6.0]) # y coordinates of 3 query points

result_bools=point_in_polygon_bitmap(pnt_x,pnt_y,f_pos,r_pos,ply_x,ply_y)
print(result_bools)

**Comment by linwoodc3** [comment]
Okay @zhangjianting .  I'll try to test this; all my previous code to test cudf/cuspatial was in the Google Colab notebook.  I'm trying to get the docker image working now.

**Comment by zhangjianting** [comment]
@linwoodc3 the purpose of setting CUSPATIAL_HOME is to locate a shapefile that comes with cuSpatial source. You can set the path to any shapefile on your machine directly.

**Comment by taureandyernv** [comment]
Additionally, for future reference, please look at this notebook to understand how to import data and use `points in polygon` https://github.com/rapidsai/cuspatial/blob/branch-0.18/notebooks/nyc_taxi_years_correlation.ipynb.  @thomcom

**Comment by thomcom** [comment]
Thanks @taureandyernv
