### ISSUE TITLE
[FEA]: Adding Spherical Surface Processing Capability to  Point-in-Polygon Queries

### ISSUE THREAD

**Issue by ayasar70** [rapidsai/cuspatial#1202]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

I would like to work on solving point-in-polygon queries using three-dimensional cartesian coordinates on spherical surfaces. Users may prefer to use that approach for more accurate computations.

#### Coordinates
I have been working on this problem on spherical surfaces. Therefore, I plan to consider that all points are in three-dimensional cartesian coordinates. However, I think proposed algorithm should work with coordinates on geodetic datum, and/or ellipsoidal surfaces. For instance, Google Earth and Oracle Spatial database uses spherical coordinates.

#### Algorithm
I plan to use a slightly updated version of the ray-casting algorithm. Since we have to solve the problem on a spherical surface instead of lines we should use arcs. First, for a test point we presume that there is an arc/curve between the test point and the first point of the query polygon. Then, similar to the ray casting algorithm we are going to count number of intersections between arcs/curves of the query polygon. Below I am going to try to provide high-level pseudo-codes.

```
let PointInPolygon(QueryPolygon Q, PointList P)
    let out = B[|P|] // array of bool for output
    for each p in P parallel do
        let arc = DefineArc(p, Q[0][0])
        let n = 0 // n defines number of intersections
        for each q in Q do // Assume q is an arc
            n += Intersects(arc, q)
        let isLeft = LeftCheck(Q[0], p)
        out[p] = ( (n%2) == isLeft)
    return out
```

In this algorithm, considering the right hand rule, to decide if a point is on the left side of an arc/curve we can use a procedure as follows:

```
let LeftCheck(Arc a, Point p)
    let o = {0, 0, 0} // Origin
    let [p1, p2] = a // begin and end points of the arc
    let p1o = o - p1
    let p2p1 = p2 - p1
    let pp1 = p3 - p1
   
    // Compute orthogonal vector
    let p1o_p2p1 = p1o (x) p2p1 // (x) -> cross product
    // Check the angle between vectors to decide 
    let w = p1o_p2p1 (.) pp1 // (.) -> dot product
    return w > 0
```

Then intersection can be computed as follows:

```
let Intersect(Arc a1, Arc a2){
    let [p1, p2] = a1
    let [p2, p3] = a2
    let p1left = LeftCheck(a2,  p1)
    let p2left = LeftCheck(a2,  p2)
    let p3left = LeftCheck(a1,  p3)
    let p4left = LeftCheck(a1,  p4)
    let alpha = p1 (.) p3
    return (p1left != p2left) && (p3left != p4left) && alpha > 0;
}

```
#### Required changes
I think this update can be implemented with minimal changes

- Add a three-dimensional vector classs
- Resolve assertion problems.
- Add spherical point-in-polygon kernels under existing point-in-polygon kernels.
- Add tests

### Describe any alternatives you have considered

I have looked at GeoPandas, but seems they do not have this capability on GPUs.

**Comment by GPUtester** [comment]
Hi @ayasar70!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
