### ISSUE TITLE
[DOC]: Readme Update for `23.08`

### ISSUE THREAD

**Issue by jarmak-nv** [rapidsai/cuspatial#1205]
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

The ST_Distance and DE9 section need updating to reflect their working status.

We also need to
- Remove the pip auto-determine `-cu11/cu12` since it finds the driver version not the CTK version
   - [Reference](https://github.com/rapidsai/docs/pull/396#discussion_r1235545923)
- Explore using [update_version.sh](https://github.com/rapidsai/cuspatial/blob/branch-23.08/ci/release/update-version.sh) to auto-increment the release version in our readme install section
- Add citation info

**Comment by bdice** [comment]
Also updating the versions in `docs/source/user_guide/cuspatial_api_examples.ipynb` would be good. It says:
```
# !conda create -n rapids-22.08 -c rapidsai -c conda-forge -c nvidia \
#     cuspatial=22.08 python=3.9 cudatoolkit=11.5
```

**Comment by harrism** [comment]
Hmmm, maybe this needs to be automated in `ci/release/update-version.sh`?
