### ISSUE TITLE
Cannot download Data for demo

### ISSUE THREAD

**Issue by andewfitting** [rapidsai/cuspatial#121]
How to access link of Data in repo

**Comment by taureandyernv** [comment]
@andewfitting the data sources I'm assuming you are looking for can be found here: https://github.com/rapidsai/cuspatial/blob/branch-0.18/data/README.md.  Also, we're moving these demos to archives and creating another notebook with easier data linking.  I'll link you to the archives if you reply to this issue and @ me, asking for the link

**Comment by thomcom** [comment]
Thanks @taureandyernv !
