### ISSUE TITLE
[QST]spatial operation like intersects?

### ISSUE THREAD

**Issue by DeoLeung** [rapidsai/cuspatial#122]
Hi, I'm exploring the library and from the python tests I found that there is window function on points (looks like bounding box intersects)

Is there, or will there be an `intersects` function like postgis to be used for `geometry` objects (not just points)?

thanks :)

**Comment by zhangjianting** [comment]
@DeoLeung Thanks for your interests in cuSpatial.  Currently we are busy with spatial indexing and indexed spatial join. Hopefully we will have time to revisit spatial window queries using the new Column and Table designs in cuDF sometime around the coming summer.  You and your team are welcome to contribute to this open source project.

**Comment by harrism** [comment]
Hi @DeoLeung , we plan to release a `intersects`  function in release 23.04. This is now tracked by #648, so I'm closing this issue.
