### ISSUE TITLE
[FEA] Remove direct use of `RMM_ALLOC`/rmm::alloc

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cuspatial#127]
**Is your feature request related to a problem? Please describe.**

RMM is likely to deprecate and remove the `RMM_ALLOC/rmm::alloc` and corresponding `RMM_FREE/rmm::free` APIs https://github.com/rapidsai/rmm/issues/302

**Describe the solution you'd like**
 Remove direct use of these APIs in favor of RAII constructs like `rmm::device_buffer` or `rmm::device_vector`. Alternatively, using the `device_memory_resource` directly from `get_default_resource()` and calling `allocate/deallocate`.

**Comment by zhangjianting** [comment]
Thanks for the suggestion. I will try to use the new APIs on all activate PRs and refactorize old code after GTC.
Just a quick question: does rmm::device_vector initialize vector elements? One problem I had with thrust::device_vector is that it always  initialize vector elements. Very often it is unnecessary to my applications and becomes a source of bottleneck.

**Comment by jrhemstad** [comment]
> Just a quick question: does rmm::device_vector initialize vector elements?

Yes, it does.

`rmm::device_buffer` does not do any initialization. 

It's future work to improve `rmm::device_vector` to accept a stream in addition to making initialization optional. See https://github.com/rapidsai/rmm/issues/120

**Comment by kkraus14** [comment]
I believe this is resolved as of 0.14. @harrism @cwharris @trxcllnt @thomcom?

**Comment by thomcom** [comment]
Yup, thanks!
