### ISSUE TITLE
[BUG]: Update usage of cudf.core.column.arange to cudf.core.column.as_column

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cuspatial#1322]
### Describe the issue

Tests are currently failing in CI, see e.g. https://github.com/rapidsai/cuspatial/pull/1321. The failures are because cuspatial uses an internal method of cudf that was removed in https://github.com/rapidsai/cudf/pull/14689. The errors can be fixed by replacing those usages in the same fashion as was done internally in that cudf PR.

**Comment by isVoid** [comment]
Resolved since #1323
