### ISSUE TITLE
[BUG] cuSpatial queries should use existing cuDF functionality where possible

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#14]
**Describe the bug**

`cuspatial::subset_trajectory_id` can be rewritten to use a `cudf::gather()`. This will enable it to automatically support null input data elements.

Likewise, `cuspatial::spatial_window_points` can probably use `cudf::copy_if` with a custom functor. Currently it uses thrust::copy_if, which can't support nulls.

**Comment by zhangjianting** [comment]
I will look into cudf::gather and cudf::copy_if. To avoid introducing last-minute bugs due to new implementations, maybe we can leave them for the next release.

**Comment by harrism** [comment]
I assigned this to myself.  The RAPIDS 0.10 release is not for weeks, we have time.
