### ISSUE TITLE
[DOC]: Remove deprecated geopandas.dataset usage in `cuspatial_api_examples.ipynb`

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cuspatial#1403]
### How would you describe the priority of this documentation request

Low (would be nice)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

`cuspatial_api_examples.ipynb` uses the `geopandas.dataset` API which has been removed in geopandas 1.0.

It would good to either:

1. Download the shape file(s) used in this notebook.
2. Rework the notebook without using an external file.  (IMO probably preferable)

Once addressed the `test_notebooks` block in `dependencies.yaml` introduced in https://github.com/rapidsai/cuspatial/pull/1400 can removed

**Comment by isVoid** [comment]
Thanks - the removal is underway in #1404
