### ISSUE TITLE
[BUG] Align utility.hpp with libcudf style

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#153]
0. Move all error handling utilities to a new header called error.hpp
1. Add a `CUSPATIAL_EXPECTS` to use in place of `CUDF_EXPECTS`. Add appropriate cuspatial exception types, e.g. `cuspatial::logic_error`.
2.  `HANDLE_CUSPARSE_STATUS` should become `CUSPARSE_TRY`. It should use `CUSPATIAL_EXPECTS` and have no raw `printf`.
3. `HANDLE_CUDA_ERROR` should become `CUDA_TRY`, identical to the one in libcudf. It should throw, not `exit()`!

**Comment by cwharris** [comment]
Investigating this.

**Comment by cwharris** [comment]
Should cuspatial's `error.hpp` be completely independant of cudf's `error.hpp`? Aka, should `CUDF_STRINGIFY` have a cuspatial variant?

**Comment by thomcom** [comment]
Thanks for looking at this! Since cudf is fundamentally a dependency of cuspatial, I don't think you need to replicate all functionality in cuspatial-only headers.

**Comment by cwharris** [comment]
I was thinking something similar. I wanted to get @harrism 's opinion on this though, since the issue description alludes to it.

**Comment by harrism** [comment]
I find it disconcerting to see `CUDF_*` macros used outside of CUDF. These are supposed to be internal details of libcudf, and they contain string error messages that are specific to CUDF. Hence my suggestion to replace them.

**Comment by thomcom** [comment]
I personally don't see a distinction between seeing `CUDF_*` in my code and seeing `cudf::` in my code. Why do you feel like the macros should not be part of the public API? They're in the headers - they're in the public API, right? :)

**Comment by cwharris** [comment]
It sounds like CUDF_* macros weren't intended to be used outside of the core repository, but the alternative is to duplicate code across repositories.

Is the problem that we haven't decided on how down-stream libcudf-related libraries should use libcudf macros, or that we _have_ decided that we _shouldn't_ use them?

**Comment by cwharris** [comment]
Specifically, it would be useful to use `CUDF_EXPECTS` or `CUDF_STRINGIFY`. Others not coming to mind at the moment.

**Comment by cwharris** [comment]
@harrism CUDA_TRY is declared in the global namespace and is included in some of the headers cuspatial includes.
