### ISSUE TITLE
[BUG] Update soa_readers.hpp to libcudf++

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#156]
* Eliminate use of gdf_column in shapefile APIs.
* Remove all raw `RMM_ALLOC/RMM_FREE` and replace with `rmm::device_buffer / device_vector`.
* Add appropriate `CUSPATIAL_EXPECTS` calls. See #153 

Also , I think in RAPIDS the concept of "SOA" is just a table, since a `cudf::table` is really just a structure of arrays. I would love to get rid of the use of "soa" and "SOA" in API names since it is an acronym that many users will not know.

**Comment by thomcom** [comment]
Refactoring out the SOA format from cuspatial is a much bigger effort than this PR, and has major implications with the python side of cuspatial as well. Cuspatial deals with large numbers of small objects, generally, like in the notebook recently submitted for PR #179. 12m lon/lat coordinates would, at the python level, create a table with 2 rows and 12m columns. That will have terrible performance implications we're not ready for yet.

**Comment by harrism** [comment]
I'm not suggesting to transpose all the data or use AOS. I'm just suggesting we get rid of the term "soa" from the APIs. It's a term users don't need to learn.

**Comment by cwharris** [comment]
#176

**Comment by trxcllnt** [comment]
Deleting the soa_readers in https://github.com/rapidsai/cuspatial/pull/206, and will update the demos to read the source JSON data directly when translating them to notebooks.
