### ISSUE TITLE
[BUG] Update point_in_polygon.hpp to libcudf++

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#158]
* Eliminate use of gdf_column in shapefile APIs.
* Remove all raw RMM_ALLOC/RMM_FREE and replace with rmm::device_buffer / device_vector.
* Add appropriate CUSPATIAL_EXPECTS calls. See #153

**Comment by cwharris** [comment]
Related resources:
- https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf
- https://wrf.ecse.rpi.edu//Research/Short_Notes/pnpoly.html
- https://postgis.net/docs/ST_IsValid.html

**Comment by harrism** [comment]
Fixed by #192 and #203
