### ISSUE TITLE
[FEA] Drop forced type conversions where appropriate

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#188]
When the python bindings were written, some or all of the cuda kernels were `float` specific. Those have since been updated to proper `cudf::column` templates, but this isn't reflected in the python yet. Remove the forced typings in python where appropriate.

This is good because it gives users much more control over their input data, and will also improve performance in any conversion case.

**Comment by trxcllnt** [comment]
Just did a quick survey, looks like everything except for CubicSpline is using the new `normalize_point_columns()` utility function to handle the floating point dtype conversion or upcasting:
https://github.com/rapidsai/cuspatial/blob/81f7d3dcc0bf76be759df1fdb772ed004e29bd80/python/cuspatial/cuspatial/utils/column_utils.py#L8-L13

Does CubicSpline need this as well?
