### ISSUE TITLE
[FEA] Point-to-polyline nearest neighbor/distance based spatial join

### ISSUE THREAD

**Issue by zhangjianting** [rapidsai/cuspatial#207]
Searching the nearest polyline feature and computing its distance is a powerful tool to align points to their neseart polylines, i.e., the nearest street segment of a taxi pickup/drop-off location.  
The nearest distance is defined as the smallest perpendicular distance to all segments of a polyline if the  perpendicular lines and the segments intersect or the smallest distance to the two ends of the segments otherwise. This seems to agree with the definition of the Symmetrized Segment-Path Distance (SSPD) discussed in https://github.com/rapidsai/cuspatial/issues/184

The point-polyline-nn based join can share the same small join framework of point-in-polygon test based spatial join, including quadtree-based spatial indexing and quadrant-bbox pairing for spatial filtering. When computing bbox of a polyline, an expansion radius R is added to return an expanded  bbox of  (x1-R,y1-R,x2+R,y2+R) for quadrant-bbox pairing. For each point in a quadrant that is assigned to a thread block, the nearest neighbor/distance computation kernel loops through all the polylines whose expanded bboxes intersect with the quadrant.  Points in quadrants that do not intersect with any expanded bbox of a polygon return no nearest neighbor/distance. Strictly speaking, this is called "Range Nearest Neighbor" or RNN spatial join, which often can be a substitute for classic NN spatial join.  
  
A preliminary implementation has been incorporated in to PRs #145, #146 and #149

**Comment by EmilioZhao** [comment]
Yes, we urgently need this feature too.

**Comment by harrism** [comment]
@trxcllnt is this issue still needed? Isn't this already implemented?

**Comment by trxcllnt** [comment]
@harrism yep, this is done

**Comment by KirkDybvik** [comment]
Curious on details of point-to-polyline, and documentation on method used?   I am interested in if "great circle" calculations would be supported.

**Comment by zhangjianting** [comment]
@KirkDybvik that would require geographical distance (on Earth surface). The current implementation only supports geometric distance on a 2D plane (after a map projection, but can be any).
