### ISSUE TITLE
[BUG] Transplant python/cuspatial/demos into notebooks and update for new APIs

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/cuspatial#209]
We should transplant the [demo](https://github.com/rapidsai/cuspatial/tree/branch-0.14/python/cuspatial/demos) python files into notebooks. We can use cuDF's `read_json()` to read the demo data instead of parsing the JSON in C++ and producing intermediate binary files.

**Comment by zhangjianting** [comment]
Agree. Good idea.

**Comment by harrism** [comment]
We should also make sure we have notebooks demonstrating newer features like spatial join and filtering
