### ISSUE TITLE
[BUG] hausdorff.cu uses custom kernel unnecessarily

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cuspatial#210]
hausdorff.cu uses a custom kernel to compute Hausdorff distances between a set of spaces.

Rather than a custom kernel, use thrust to eliminate the one-result-per-warp limitation and flatten nested loops. Hypothetically this should increase performance, especially when processing more spaces of different sizes.

- [x] Create Hausdorff Benchmarks
- [x] Replace custom kernel
- [x] Verify performance is at least as good as the custom kernel.

**Comment by zhangjianting** [comment]
There are trade-offs between degree of parallelism and the overhead of materializing intermediate results in global memory. Benchmarking on large-scale and real data will help to make the decision.

**Comment by cwharris** [comment]
Pointing to a comment with a description of how I'll approach this. It's vague, but we can extrapolate in this issue. https://github.com/rapidsai/cuspatial/pull/174#discussion_r421844937

**Comment by cwharris** [comment]
Thrust issue proposing a parallel accumulate/accumulate_by_key which supports non-commutative operations: thrust/thrust#596

**Comment by cwharris** [comment]
https://github.com/rapidsai/cuspatial/pull/246
