### ISSUE TITLE
[QST] Can't install using suggested methods in a docker container

### ISSUE THREAD

**Issue by mbforr** [rapidsai/cuspatial#213]
**What is your question?**

hi there! trying to get this package pulled into a custom environment as i primarily use pip envs. i found a docker set up and was able to get it installed but it is giving me an error from the install instructions here that says python 3.7 is not compatible with the package. that was using this install:

`conda install -c conda-forge -c rapidsai-nightly cuspatial`

when i try the install method in the main conda listing it completes but then when i import the library it says that it has an improper install of `cupy`.

any ideas or best practices i can try here?

**Comment by thomcom** [comment]
Thanks for taking a look @mbforr. I'm going to look into your problem today.

**Comment by mbforr** [comment]
great thank you! i tried to use this standard container first:

https://hub.docker.com/r/continuumio/anaconda/

as well as this one:

http://www.science.smith.edu/dftwiki/index.php/Tutorial:_Docker_Anaconda_Python_--_4

no luck on either. the first one installs python 3.7 and the later 3.6

**Comment by thomcom** [comment]
Have you tried one of our dedicated containers at https://rapids.ai/start.html ? Use the rapids release selector to get a docker container that is preconfigured.

**Comment by mbforr** [comment]
i have not - trying that now!

**Comment by mbforr** [comment]
FYI i tried the google collab notebook and got this error:

<img width="917" alt="Screen Shot 2020-05-21 at 12 09 14 PM" src="https://user-images.githubusercontent.com/4828460/82579770-45e2a800-9b5c-11ea-87a3-27903839da24.png">

are the docker containers the recommended route for using the libraries?

**Comment by miltongneto** [comment]
I had the same problem to import the cuspatial, but I installed with conda in a new environment.
I fixed it by installing the missing package.

**conda install -c conda-forge libwebp**

It worked for me.

**Comment by harrism** [comment]
closing as out of date. Please reopen if this is still an issue.
