### ISSUE TITLE
[DOC] geometry formats

### ISSUE THREAD

**Issue by achapkowski** [rapidsai/cuspatial#241]
**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

Where can I find documentation on the geometry format?

**Describe the documentation you'd like**

If it doesn’t exist, provide samples of how geometries must be formatted for product interop.

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by trxcllnt** [comment]
Hi @achapkowski, this [docstring](https://github.com/rapidsai/cuspatial/blob/9f21d5ad1e6caaf64f2127297e761d9a38ac4711/python/cuspatial/cuspatial/core/gis.py#L194-L201) includes an example of the format (and [here's](https://www.desmos.com/calculator/sutbohpv0f) a visual).

The layout is roughly equivalent to a List of Lists of points:
* `poly_offsets` are the start positions of elements in `ring_offsets`
* `ring_offsets` are start positions of elements in `poly_point_x` and `poly_point_y`

If the polygons are not closed (as in the example), the start point is assumed to be the closing end point.

**Comment by achapkowski** [comment]
How do you handle holes?

**Comment by zhangjianting** [comment]
> How do you handle holes?

https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf

**Comment by harrism** [comment]
we should improve the documentation of geometry formats.

**Comment by achapkowski** [comment]
Thank you, I would appreciate that.

**Comment by harrism** [comment]
@thomcom @isVoid is this covered by the recently merged Python doc PRs?

**Comment by isVoid** [comment]
Recent refactoring and documentation has made it clear that cuSpatial will adapt to GeoArrow format. This should be covered.
