### ISSUE TITLE
[BUG] ImportError: libgdal.so.26: cannot open shared object file: No such file or directory in nightly container

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cuspatial#275]
**Describe the bug**
When importing `cuspatial` I got this ImportError: libgdal.so.26: cannot open shared object file: No such file or directory in nightly container.

**FULL TRACE**

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-aa33e033382d> in <module>
      1 import cudf
----> 2 import cuspatial
      3 from collections import OrderedDict
      4 import numpy as np
      5 import datetime as dt

/opt/conda/envs/rapids/lib/python3.7/site-packages/cuspatial/__init__.py in <module>
----> 1 from .core import interpolate
      2 from .core.gis import (
      3     directed_hausdorff_distance,
      4     haversine_distance,
      5     lonlat_to_cartesian,

/opt/conda/envs/rapids/lib/python3.7/site-packages/cuspatial/core/interpolate.py in <module>
      6 from cudf import DataFrame, Series
      7 
----> 8 from cuspatial._lib.interpolate import (
      9     cubicspline_coefficients,
     10     cubicspline_interpolate,

ImportError: libgdal.so.26: cannot open shared object file: No such file or directory
```

**Steps/Code to reproduce bug**
`import cuspatial` should load the library.

**Expected behavior**
Should load the library.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuSpatial install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

   -- **PULL**: docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7
   -- **RUN**:

```
docker run --gpus all -it -p 8888:8888 -p 8787:8787 -p 8786:8786 --name kdd_rapids \
	rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7
```
 

**Additional context**

**Comment by cwharris** [comment]
Hi @drabastomek, what version of gdal is currently installed in the container?

**Comment by thomcom** [comment]
Looks like it is gdal 3.1.2 @cwharris

**Comment by drabastomek** [comment]
As @thomcom suggested -- current version is GDAL 3.1.2, released 2020/07/07. 

The workaround that got me unblocked involved commenting out portions of the `__init__.py` and also copying the `libdgal.so.27` to `libgdal.so.26` (I only needed the `haversine_distance` so that was fine).

**Comment by trxcllnt** [comment]
I think this was the same issue we filed https://github.com/rapidsai/cuspatial/pull/375 to fix?
