### ISSUE TITLE
[FEA] Provide version number for Python bindings

### ISSUE THREAD

**Issue by stev-0** [rapidsai/cuspatial#283]
**Is your feature request related to a problem? Please describe.**
I'm using the Docker container for RAPIDS 0.15 and running the cuSpatial examples.
I noticed there doesn't seem to be a way to determine the version. I know this is related to the globally installed version of RAPIDS at least in this case but it might be clearer if there was one for cuSpatial itself.

**Describe the solution you'd like**
A `_version` module as in the `cudf` package

**Describe alternatives you've considered**
Documentation about how to get the version number from other required components, e.g. `cudf`

**Comment by harrism** [comment]
@kkraus14 @thomcom would this be an easy fix?

**Comment by thomcom** [comment]
Heya, version number coming up in #399.
