### ISSUE TITLE
[BUG] No yml file for CUDA 11.0 dev environment

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cuspatial#301]
The yml file for creating a dev environment with CUDA 11.0 is not present in the `conda/environments/`  folder.

**Comment by Salonijain27** [comment]
Thoughts on adding :
```
  - cmake>=3.14
  - cmake_setuptools>=0.1.3
```
to the yml files?

**Comment by harrism** [comment]
As a non-conda expert, seems fine to me. @kkraus14, @jakirkham or @thomcom any opinions?

**Comment by kkraus14** [comment]
We shouldn't need `cmake_setuptools` as far as I'm aware, otherwise LGTM
