### ISSUE TITLE
[BUG] The directed_hausdorff_distance returns wrong values

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cuspatial#316]
**Describe the bug**
The `directed_hausdorff_distance` returns wrong values that are not matching the docs.

**Steps/Code to reproduce bug**
Minimal example:
```
result = cuspatial.directed_hausdorff_distance(
        [0, 1, 0, 0], # xs
        [0, 0, 1, 2], # ys
        [2,    2],    # points_per_space
    )

print(result)
```

prints out

```
               0    1
0  4.880590e-313  2.0
1  8.912382e-313  0.0
```

What's more, restarting the kernel changes the output every time (the precision). Loading a data into GPU memory changes tha values as well...

```
ring, poly_idx, polygons = cuspatial.io.shapefile.read_polygon_shapefile('../data/gadm36_USA_1.shp')
```

produces

```
               0              1
0  2.015896e-312  2.204754e-311
1  2.716155e-312   0.000000e+00
```

**Expected behavior**
The return should print out

```
       0     1
0   0.00  1.41
1   2.00  0.00
```

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuSpatial install: Docker
   - Stable git pull from rapidsai/rapidsai, v 0.16, CUDA 11, Python 3.7.8

**Comment by zhangjianting** [comment]
@drabastomek The minimal example works fine on my machine (Titan RTX). To reproduce your error using the shapefile, can you share the shapefile? Thanks.

**Comment by zhangjianting** [comment]
I was  able to reproduce bug at C++ level. See  [debug code](http://geoteci.engr.ccny.cuny.edu/cuspatial/hausdorff_debug.cpp) 

Interestingly, the 3 space test works just fine. 
The actual outputs of the 2 and 3 space tests are embedded.  

In addition, when uncomment "expect_columns_equivalent(expected, actual->view(), true);" in the 2-space test, I got the following memory related error: 

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorLaunchFailure: unspecified launch failure
Aborted (core dumped)

Is the 2-space case a corner case for the most recent C++ implementation?

**Comment by harrism** [comment]
@cwharris any insight?

**Comment by cwharris** [comment]
Hmm... I'm having trouble building cuspatial at the moment, but I can take a look at this tomorrow.

**Comment by cwharris** [comment]
@zhangjianting hausdorff requires offsets and not sizes:
```
 auto space_offsets = cudf::test::fixed_width_column_wrapper<cudf::size_type>({2,2});
```
and should instead be
```
 auto space_offsets = cudf::test::fixed_width_column_wrapper<cudf::size_type>({0,2}); // <= { 0, 2 } vs { 2, 2 }
```

**Comment by cwharris** [comment]
@drabastomek It appears I forgot to update the documentation for Hausdorff on the python side (and some on the cpp side as well). The implementation accepts offsets of the first point in each space, not the number of points per space. So this code:
```python
result = cuspatial.directed_hausdorff_distance(
        [0, 1, 0, 0], # xs
        [0, 0, 1, 2], # ys
        [2,    2],    # points_per_space
    )
```
needs to be:
```python
result = cuspatial.directed_hausdorff_distance(
        [0, 1, 0, 0], # xs
        [0, 0, 1, 2], # ys
        [0,    2],    # points_per_space
    )
```
This would explain the results differing per run, as certain values may never be assigned, leaving uninitialized bits to run amok.

It would be ideal if we could catch these things at run time, but that would require a device-to-host copy, or an additional kernel launch (which might be doable as an option, actually...).

**Comment by zhangjianting** [comment]
@cwharris You are right. I missed that part.

**Comment by harrism** [comment]
Adding doc label and assigning to @cwharris for 0.17. Chris let me know if you don't have time for this in the current release and we can reassign. Thanks!

**Comment by drabastomek** [comment]
@cwharris Great that this is a simple change!!! 
@zhangjianting @harrism Thanks for pushing this!
