### ISSUE TITLE
[BUG] Haversine distance doesn't return proper distances

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cuspatial#317]
**Describe the bug**
It's unclear whether the distance returned is in mls or kms (the documentation doesn't state that). However, the returned value matches neither.

**Steps/Code to reproduce bug**
Quick example

```
from math import sin, cos, sqrt, pi, asin

def calculateDistance(latitude, longitude, LAT_Ref, LON_Ref, distance_km, distance_mls):
    for i, (lat, lon, lat_r, lon_r) in enumerate(zip(latitude, longitude, LAT_Ref, LON_Ref)):
        lat_rad = lat * pi / 180.0
        lat_r_rad = lat_r * pi / 180.0
        delta_lon = (lon_r - lon) * pi / 180.0
        delta_lat = (lat_r - lat) * pi / 180.0
        
        temp = (sin(delta_lat / 2.0)**2
               + cos(lat_rad)*cos(lat_r_rad) * (sin(delta_lon / 2.0))**2)
        distance_km[i] = 2 * asin(sqrt(temp)) * 6371
        distance_mls[i] = 2 * asin(sqrt(temp)) * 3958.8

small_example = cudf.DataFrame([
    (-87.97000122, 30.67666626),
    (-87.97166443, 30.67666626),
    (-87.97194672, 30.67638969),
    (-87.97222137, 30.67638969),
    (-87.97222137, 30.67527771)
], columns=['lon', 'lat'])

us_center = [39.8333333, -98.585522]
small_example['us_center_lat'] = us_center[0]
small_example['us_center_lon'] = us_center[1]

small_example['distance_cuspatial'] = cuspatial.haversine_distance(
    small_example['lat']
    , small_example['lon']
    , small_example['us_center_lat']
    , small_example['us_center_lon']
)

small_example = small_example.apply_rows(
    calculateDistance
    , incols={'lat':'latitude', 'lon':'longitude', 'us_center_lat':'LAT_Ref', 'us_center_lon':'LON_Ref'}
    , outcols={'distance_km':np.float64, 'distance_mls':np.float64}
    , kwargs={}
    , pessimistic_nulls=False
)

small_example.head()
```

returns the following

lon | lat | us_center_lat | us_center_lon | distance_cuspatial | distance_km | distance_mls
 -- | -- | -- | -- | -- | -- | --
-87.970001 | 30.676666 | 39.833333 | -98.585522 | 1178.059263 | 1399.979064 | 869.916358
-87.971664 | 30.676666 | 39.833333 | -98.585522 | 1177.875874 | 1399.875842 | 869.852218
-87.971947 | 30.676390 | 39.833333 | -98.585522 | 1177.844607 | 1399.881723 | 869.855872
-87.972221 | 30.676390 | 39.833333 | -98.585522 | 1177.814323 | 1399.864679 | 869.845282
-87.972221 | 30.675278 | 39.833333 | -98.585522 | 1177.813758 | 1399.958761 | 869.903742

The numbers in the `distance_km` and `distance_ml` are confirmed to be correct with external calculators.

**Expected behavior**
Distance in either miles or kms returned

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuSpatial install: Docker
   - Stable git pull from rapidsai/rapidsai, v 0.16, CUDA 11, Python 3.7.8

**Comment by zhangjianting** [comment]
@drabastomek 
The cuspatial.haversine_distance API requires for columns (lon1,lat1,lon2,lat2). I think your lon/lat order is swapped. You should get correct results after you switch the order. The reason we use (lon,lat) rather than (lat, lon) is because lon-->x, lat-->y. 
The distance is in the unit of km. We should have made it clear.

**Comment by drabastomek** [comment]
Got it! Yes, swapping the lon with lat worked. Closing.
