### ISSUE TITLE
[DOC] Units for haversine_distance

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cuspatial#324]
## Report needed documentation

The `cuspatial.haversine_distance` function does not document the output units.

https://docs.rapids.ai/api/cuspatial/stable/api.html#cuspatial.haversine_distance

By comparing the outputs with other tools for calculating this I assume the output is in km. 

It would be good to clarify this in the docstring and also what earth radius was used when converting to distance.

**Comment by drabastomek** [comment]
Same issue #137

**Comment by harrism** [comment]
Closing as duplicate.
