### ISSUE TITLE
[DOC] Documentation for cuspatial.polyline_bounding_boxes does not match the function signature

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cuspatial#336]
## Report incorrect documentation
Trying to pass `poly_offsets`, `ring_offsets`, `xs`, and `ys` results in a `TypeError: must be real number, not Series`

**Location of incorrect documentation**
https://docs.rapids.ai/api/cuspatial/nightly/api.html?highlight=polyline_bounding#cuspatial.polygon_bounding_boxes

**Describe the problems or issues found in the documentation**
Wrong function signature

**Steps taken to verify documentation is incorrect**
Run the following code

```
import cuspatial

ring, poly_idx, polygons = cuspatial.io.shapefile.read_polygon_shapefile('../data/gadm36_USA_1.shp')
polygons = polygons.rename(columns={'x': 'longitude', 'y': 'latitude'})
# polygons['line'] = cp.random.randint(10,240, len(polygons))
polygons = polygons.query(
        'longitude > -130'
        ' and longitude < 70'
        ' and latitude < 50'
    )

bounding_boxes = cuspatial.polyline_bounding_boxes(
    poly_idx
    , ring
    , polygons['longitude']
    , polygons['latitude']
)
```

throws

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-eff4477c8792> in <module>
----> 1 bounding_boxes = cuspatial.polyline_bounding_boxes(
      2     poly_idx
      3     , ring
      4     , polygons['longitude']
      5     , polygons['latitude']

/opt/conda/envs/rapids/lib/python3.8/site-packages/cuspatial/core/gis.py in polyline_bounding_boxes(poly_offsets, xs, ys, expansion_radius)
    324     xs, ys = normalize_point_columns(as_column(xs), as_column(ys))
    325     return DataFrame._from_table(
--> 326         cpp_polyline_bounding_boxes(poly_offsets, xs, ys, expansion_radius)
    327     )

cuspatial/_lib/polyline_bounding_boxes.pyx in cuspatial._lib.polyline_bounding_boxes.polyline_bounding_boxes()

TypeError: must be real number, not Series
```

Looking at the method signature https://github.com/rapidsai/cuspatial/blob/a1f7120728c25555431508fe9427a79c4bbb9f1c/python/cuspatial/cuspatial/core/gis.py#L295 shows the discrepancy.

Changing the call to correct signature still throws an error: #335

**Comment by trxcllnt** [comment]
@drabastomek I think this might've been due to the docs rendering issue fixed in https://github.com/rapidsai/cuspatial/pull/298. The `polyline_bounding_boxes` should take the `polyline_offsets`, `xs`, `ys`, and `expansion_radius`. Let us know if those still aren't working for you and we can figure out why.

**Comment by thomcom** [comment]
Actually you're reading the `polygon_bounding_boxes` docs, just below it is the `polyline_bounding_boxes` docs that say `offsets, xs, ys, radius`.

The difference in the two sigs is that `polygon_bounding_boxes` requires a set of `polygon` offsets (arg 0) and a set of `ring` offsets (arg 1). `polyline_bounding_boxes` requires a set of `polyline` offsets (arg 0) and an `expansion_radius` (arg 3) that specifies how thick the lines should be.
