### ISSUE TITLE
[BUG] Timestamp parameter to `derive` appears to be redundant

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#34]
**Describe the bug**
Derive returns results that do not include any timestamp relevant information. Is it actually used in the computation, or can it be removed?

**Steps/Code to reproduce bug**
```
        import cudf
        import cuspatial
        result = cuspatial.derive(
            cudf.Series([0, 1, 2, 3]),
            cudf.Series([0, 0, 1, 1])
            cudf.Series([0, 0, 1, 1])
            cudf.Series([0, 10, 0, 10])
        )
        print(result)
        (2,    trajectory_id  length  position
         0              0       2         2
         1              1       2         4)
```

**Comment by zhangjianting** [comment]
I will look into this.

**Comment by zhangjianting** [comment]
derive_trajectories() sorts points based on objectID+timestamp. In addition to trajectory_id/length/position, which are trajectory level info, x/y/objectID/timestamp should also be part of  the output (sorted data). length/position index on the sorted output data and it would be incorrect to index the input data. As such, returning two dataframes is needed.

**Comment by taureandyernv** [comment]
@thomcom, may we close?

**Comment by thomcom** [comment]
Thanks @taureandyernv
