### ISSUE TITLE
[FEA] Archiving Demo Scripts

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuspatial#341]
Following https://github.com/rapidsai/cuspatial/issues/312, we're moving the cuSpatial demo scripts to Community Notebooks Archive

To do:
- [ ] Identify Demo scripts that should be converted to notebook form
- [ ] SWIPAT data for those scripts to become notebooks
- [ ] Move data to S3 Bucket
- [ ] Move all scripts to Community Notebooks Archive, with data README
@aravenel @thomcom @zhangjianting

**Comment by thomcom** [comment]
Wonder if this is still on your radar @taureandyernv ?

**Comment by harrism** [comment]
I unchecked "Identify Demo scripts that should be converted to notebook form" because there's no evidence that this was ever done.

**Comment by harrism** [comment]
@taureandyernv are you planning to work on this issue?
