### ISSUE TITLE
[BUG]derive_trajectories error with cudf.Series input

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cuspatial#351]
On passing cudf.Series as the input for `cuspatial.derive_trajectories` function. I get the following error :
```
RuntimeError: scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
However, when I pass in `numpy.ndarray` obtained by using cudf's `to_array()` function I dont see the above error.

Issue #350  shows that this error seems to be due to the size of the column. However, converting cudf.Series into numpy.ndarray should be consuming more memory.

Dataset:
The dataset used is schema_HWY_20_AND_LOCUST-filtered.json. The link to download this dataset is provided in cuspatial/data folder.
Length of the column being passed is 1305760.

Environment detail :
I am running the code on a 32GB GV100 which has CUDA 11.0 installed on it. In addition, I installed the cuspatial library from source and conda installed the latest version of cudf .

Code:
```
import cudf
import cuspatial
df = cudf.read_json(
    'data/schema_HWY_20_AND_LOCUST-filtered.json', lines=True
)[["object", "@timestamp", "location", "lon", "alt"]]
# cudf.read_json has a few bugs reading nested JSON, so clean up a few
# names and cast to the correct dtypes
df = cudf.DataFrame({
    "longitude": df["lon"],
    "altitude": df["alt"].str.slice(0, -1).astype("float64"),
    "object_id": df["object"].str.slice(len('{"id":"')).astype("int32"),
    "latitude": df["location"].str.slice(len('{"lat":')).astype("float64"),
    "timestamp": df["@timestamp"].str.replace('-', '') \
                                 .str.replace('T', ' ') \
                                 .str.replace('Z', '') \
                                 .astype("datetime64[ms]")
})[["object_id", "longitude", "latitude", "altitude", "timestamp"]]
print(df.dtypes)
print("")
print(df.head())

ys = df.longitude.to_array()
xs = df.latitude.to_array()
ts = df.timestamp.to_array()
ids = df.object_id.to_array()

num_traj, trajectories = cuspatial.derive_trajectories(ids, xs, ys, ts)
```
Please comment out `to_array()` function for `xs`, `ys`, `ts` and `ids` to see the above mentioned error.

**Comment by thomcom** [comment]
Duplicates #350 it is a json reader bug.
