### ISSUE TITLE
[BUG] `cuspatial.read_its_timestamps` isn't cudf compatible

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#36]
**Describe the bug**
The SOA form of timestamps isn't immediately compatible with cudf. SOA timestamps are a specific 64 bit binary format with regions for y,m,d,hh,mm,ss,wd,yd,ms, and pid. These regions all need to be computed into a single datetime value to be compatible with cudf.

**Comment by thomcom** [comment]
It's been proposed I think by @harrism that we should remove `its_timestamp` from cuspatial entirely. How do you feel about that, @zhangjianting?

It is straightforward given the current `its_timestamp` code and data for me to convert it all to `datetime64[ms]` format, based on linear numpy timestamps. Is that ok with you @zhangjianting? Or is this timestamp format a common GIS case we need to maintain support for?

**Comment by zhangjianting** [comment]
OK with me.

**Comment by harrism** [comment]
Excellent. Note that cuDF is also starting the process of adopting a new timestamp based on C++ `std::chrono`. Using C++ standards is a good thing™️, so it's good to stick with cuDF in this respect.

**Comment by thomcom** [comment]
This is closed out, thanks for pointing it out @taureandyernv
