### ISSUE TITLE
[BUG] Update cuspatial's cudf verison to 0.19 and 0.20

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuspatial#381]
**Describe the bug**
your cudf version on the yaml is `0.16.*`

**Steps/Code to reproduce bug**
Go to https://github.com/rapidsai/cuspatial/blob/branch-0.20/conda/environments/cuspatial_dev_cuda11.0.yml.

**Expected behavior**
It should be up to date with current cudf 

**Additional context**
Going back in time, This hasn't been changed since 0.16/Oct 2020 :)

**Comment by thomcom** [comment]
resolved
