### ISSUE TITLE
[DOC/QST] Scale parameter in quadtree methods

### ISSUE THREAD

**Issue by buckeye17** [rapidsai/cuspatial#397]
The API documentation describes the `scale` parameter as, "Scale to apply to each point’s distance from (x_min, y_min)."  While this is comprehensible, I'm struggling to understand why someone would want to change it.  Is it so that the location data can be kept in coordinate reference frame, while outputs for trajectories, etc. can be given in another?  I've looked over the demos and examples and can't find any explanation for why this feature is useful, and I'm not sure how it affects the quadtree results, if at all.  Thanks for any clarification you can provide!

**Comment by zhangjianting** [comment]
quadtrees work on a discrete space. scale, together with x_min and y_min, defines the configuration of the grid that a quadtree works on. The smaller the scale, the more rows/columns of the grid and typically the larger and the deeper of the resulting quadtree. That being said, the tradeoff between filtering and refinement (for spatial join and other query types) when utilizing quadtree indexing does not have a definite relationship with scale (or grid resolution). 
Ideally, a "smarter" indexing technique can determine scale automatically but it is still pretty much an open research question. As such, cuspatial allows users to specify scale for better control. It is understandable that some background expertise is needed. Hopefully the slides at following link can provide some additional info https://github.com/zhangjianting/cuspatial/blob/fea-spatial-join/docs/quadtree_indexing_spatial_join.pdf

**Comment by harrism** [comment]
We should add more of an explanation as provided by @zhangjianting to the documentation for this function.

**Comment by harrism** [comment]
@trxcllnt can you add the explanation as part of your refactoring?

**Comment by harrism** [comment]
We need to update the documentation here: https://github.com/rapidsai/cuspatial/blob/930a2f33953ce1abe8f0680ebbf418675db4b362/python/cuspatial/cuspatial/core/spatial/indexing.py#L35

We should also provide default values for scale, max_depth.

Also the Python API for min_size needs to be updated to match max_size in the C++ API.

Discussion:
* Scale is not a great name, since we divide by it. Almost a normalization factor?

**Comment by harrism** [comment]
@trxcllnt can we also consider this issue fixed by #797 ?
