### ISSUE TITLE
[BUG] point_in_polygon_bitmap index alignment may be off

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cuspatial#46]
Surfaced this with @thomcom . There may be something going on with the array offsetting. Example tweaked from the pytest.

EDIT: This appears to be non-deterministic or perhaps undefined indexing behavior?

```python
import numpy as np
import pytest
​
import cudf
from cudf.utils import cudautils
from cudf.tests.utils import assert_eq
​
import cuspatial
​
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 13]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   4, 8, 6]),
    )
​
print(cudf.Series(result))
​
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 14]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   4, 8, 6]),
    )
​
print(cudf.Series(result))
​
​
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 15]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   4, 8, 6]),
    )
​
print(cudf.Series(result))
​
0    3
1    1
2    2
3    3
dtype: int32
0    7
1    1
2    2
3    7
dtype: int32
0    3
1    5
2    2
3    3
dtype: int32
```

**Comment by beckernick** [comment]
Non-determinism:

```python
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 14]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   4, 8, 6]),
    )
​
print(cudf.Series(result))
​
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 14]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   4, 8, 6]),
    )
​
print(cudf.Series(result))
0    7
1    1
2    2
3    7
dtype: int32
0    3
1    1
2    2
3    3
dtype: int32
```

**Comment by zhangjianting** [comment]
The beginning and the ending vertices  of rings  polygons have to be the same.  The 3rd polygon in your example is a triangle with 4 vertices. You only provided 3 vertices which is incorrect. 
The C++ backend should have checked the last element of r_pos column (14 in this example) and the size of x/y columns of the inputs (13 in this example).

**Comment by zhangjianting** [comment]
The last polygon should have 4 vertices (the first and the last should be the same). Please take a look at https://en.cppreference.com/w/cpp/algorithm/inclusive_scan or 
https://thrust.github.io/doc/group__prefixsums_gafb24ad76101263038b0acaddc094d70a.html#gafb24ad76101263038b0acaddc094d70a
for your test, I would use 
result = cuspatial.point_in_polygon_bitmap(
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([0, -8, 6.0, 3]),
        cudf.Series([1,2,3]), # three polygons
        cudf.Series([5, 10, 14]),
        cudf.Series([-10.0, 5, 5, -10, -10, 0, 10, 10, 0, 0,   2,4, 8, 2]),
        cudf.Series([-10.0, -10, 5, 5, -10, 0, 0, 10, 10, 0,   6,4, 8, 6]),
    )
​
print(cudf.Series(result))
​
0    3
1    1
2    2
3    3

**Comment by beckernick** [comment]
Ahhh, I see now. This was the core misunderstanding I had (I'm not that knowledgable of geospatial patterns). I think we should consider making this explicit in the docstring

**Comment by thomcom** [comment]
I didn't know we needed to have closed polygons either! Thanks @zhangjianting for clearing that up. No wonder! I will put this into the docs.

**Comment by beckernick** [comment]
cc @randerzander for your notebook
