### ISSUE TITLE
[DOC] The column order returned from `quadtree_point_in_polygon` does not match what is described in the API doc.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cuspatial#489]
## Report incorrect documentation
[The doc](https://github.com/rapidsai/cuspatial/blob/90be36d1348adef236ffd14abf1829820a46040b/cpp/include/cuspatial/spatial_join.hpp#L94) tells `quadtree_point_in_polygon` will return the (point_offset, polygon_offset) pair, but [the implementation](https://github.com/rapidsai/cuspatial/blob/90be36d1348adef236ffd14abf1829820a46040b/cpp/src/join/quadtree_point_in_polygon.cu#L169) actually returns (polygon_offset, point_offset) pair.

**Comment by zhangjianting** [comment]
The Cython API also shows that the order is (polygon_offset, point_offset). https://github.com/rapidsai/cuspatial/blob/90be36d1348adef236ffd14abf1829820a46040b/python/cuspatial/cuspatial/_lib/spatial_join.pyx#L80
