### ISSUE TITLE
[FEA] `polyline` -> `linestring`?

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#520]
In general, `polyline` and `linestring` both refers to a data structure that contains multiple points with the line segments that connect the points. `Linestring` is standardized in GIS systems through OGC-SFS and provides a lot more relevant search results in [google search](https://www.google.com/search?q=linestring) as compared to [search with polyline](https://www.google.com/search?q=polyline).

After introduction of #510 there will be two different names of the same concept. I would propose naming `polyline` with `linestring` in the code base to avoid confusion.

**Comment by harrism** [comment]
Did "polyline" already exist in the codebase?

**Comment by isVoid** [comment]
Yes, in cpp:
https://github.com/rapidsai/cuspatial/blob/8c31c2cad9cc333813848b2e33bb6d0fd884ed6b/cpp/src/spatial/polyline_bounding_box.cu#L57

https://github.com/rapidsai/cuspatial/blob/6a34c21ac13708303cda7c2fb9c49fbb42d04ed5/cpp/include/cuspatial/spatial_join.hpp#L151

in python:
https://github.com/rapidsai/cuspatial/blob/92266b6cd88d3283eef45b0a38e712a250f14bdf/python/cuspatial/cuspatial/core/gis.py#L305

https://github.com/rapidsai/cuspatial/blob/92266b6cd88d3283eef45b0a38e712a250f14bdf/python/cuspatial/cuspatial/core/gis.py#L305

**Comment by isVoid** [comment]
`Linestring` isn't the first time showing up in the code base either:
https://github.com/rapidsai/cuspatial/blob/92266b6cd88d3283eef45b0a38e712a250f14bdf/python/cuspatial/cuspatial/io/geopandas_adapter.py#L59

**Comment by thomcom** [comment]
I support this renaming. I think polyline is possibly older, and has moved toward linestring. Primarily I'm pretty sure it just heralds from a slightly different GIS community than ours. Linestring it is, for me.
