### ISSUE TITLE
[FEA] Refactor trajectory APIs to header-only API

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#563]
Create header-only APIs for the following and refactor existing APIs / tests on top of the header-only API:

- [x] `cuspatial::derive_trajectories` #628 
- [ ] `cuspatial::trajectory_distances_and_speeds`
- [x] `cuspatial::trajectory_bounding_boxes`

See https://github.com/rapidsai/cuspatial/blob/branch-22.08/cpp/include/cuspatial/trajectory.hpp

https://github.com/rapidsai/cuspatial/issues/563#tasklist-block-0ad734e5-e92a-454a-bf8e-72701ce77eb6

**Comment by jarmak-nv** [comment]
@isVoid to help unblock
