### ISSUE TITLE
[FEA] Refactor Spatial Join APIs to header-only

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#565]
Create header-only APIs for the following and refactor existing APIs / tests on top of the header-only API:

See https://github.com/rapidsai/cuspatial/blob/branch-22.08/cpp/include/cuspatial/spatial_join.hpp

`cuspatial::join_quadtree_and_bounding_boxes()` completed by #861 

```[tasklist]

- [x] Header-only join_quadtree_and_bounding_boxes
- [ ] #985
- [ ] #986
- [ ] https://github.com/rapidsai/cuspatial/issues/1006
- [ ] https://github.com/rapidsai/cuspatial/issues/1007
```

**Comment by jarmak-nv** [comment]
Completed with #861

**Comment by trxcllnt** [comment]
@jarmak-nv there's two more methods this issue describes, so we've been keeping it open until they're all done.

**Comment by jarmak-nv** [comment]
Oh apologies! I just saw status done. I'll reach out to confirm in the future.
