### ISSUE TITLE
[BUG] Pairwise linestring distance should return one past the last written output iterator

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#576]
According to [development doc](https://github.com/rapidsai/cuspatial/blob/branch-22.08/cpp/doc/libcuspatial_refactoring_guide.md#example-api), to be consistent with `std::transform` API, the method should return the output iterator to one past the last element being written to by the algorithm. Currently, pairwise linestring distance returns `void`:
https://github.com/rapidsai/cuspatial/blob/dbebf67d422104dc47e8ed2ac5a6d2ec75e2e8d0/cpp/include/cuspatial/experimental/linestring_distance.cuh#L61

**Comment by harrism** [comment]
> to be consistent with `std::transform` API, the method should return the output iterator to one past the last element being written to by the algorithm. 

Not specifically `transform`, but to match the style of the STL and Thrust in general.

**Comment by harrism** [comment]
> to be consistent with `std::transform` API, the method should return the output iterator to one past the last element being written to by the algorithm. 

Not specifically `transform`, but to match the style of the STL and Thrust in general.
