### ISSUE TITLE
[DOC] Improve Python developer documentation

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#599]
We would like to improve cuSpatial's developer documentation to make it easier to contribute to cuSpatial.

I think we should follow the lead of cuDF, which has a relatively comprehensive set of documentation for developers. [cuDF provides](https://github.com/rapidsai/cudf/tree/branch-22.08/docs/cudf/source/developer_guide) a `library_design.md` which provides an overview of the core classes and their relationships. It also provides `documentation.md` which documents how developers should write docstrings for cuSpatial Python APIs.

cuDF is in the process of further improving its Python developer guides, which will provide even better examples for cuSpatial. For example, there are PRs for [creating the main Python developer guide](https://github.com/rapidsai/cudf/pull/11235), [adding developer docs for writing tests,](https://github.com/rapidsai/cudf/pull/11199), and [adding developer docs for benchmarking](https://github.com/rapidsai/cudf/pull/11235). (All by @vyasr)

In addition to developer docs, cuDF also provides a comprehensive [user guide](https://github.com/rapidsai/cudf/tree/branch-22.08/docs/cudf/source/user_guide). This is helpful to developers as well as to users.  We should consider this for cuSpatial as well.

**Comment by thomcom** [comment]
The python User Guide is ready for review in and should close or contribute greatly to this issue. https://github.com/rapidsai/cuspatial/pull/666
