### ISSUE TITLE
[DISCUSSION] `ST_DISTANCE` Method Namings

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#607]
Orginally ported from https://github.com/rapidsai/cuspatial/pull/558#discussion_r906307896

Considering the `st_distance` covers many geometry combinations, there needs to be a way to make each distance primitive easy to find by users. 

## File Organizations
All distances files should live under `distance` folder. Name of the file should include the name of geometries in the operation, ranking from low dimension to high dimension. For example, methods computing distances between point and linestring distance should be placed in `point_linestring_distance.cuh`.

## Method namings
The method should be prepended with the parallel model, which could be either `pairwise` or `all_pairs`. Followed by the type of the distance operator. In order to support reflected operation between geometries, there can be an extra argument "reflected" for control. For example, `pairwise_point_linestring_distance` vectorizes computation between an array of point and an equal length array of linestrings.

**Comment by harrism** [comment]
Should mention the rule for when testing the same geometry, e.g. point-to-point distance. Is it named `pairwise_point_to_point_distance` or `pairwise_point_distance`?

Should we consider making the distance metric a parameter of these methods? Then the current "haversine" distance would go away, and a haversine metric would be a parameter to `pairwise_point_distance`. `directed_hausdorff_distance` would become `all_pairs_point_distance` with a `directed_hausdorff` metric parameter.

Ultimately the types of the first and second geometries could be parameters of a higher level `distance()` API which dispatches to these lower-level APIs.

**Comment by isVoid** [comment]
I think the discussion is settled. Closing.
