### ISSUE TITLE
[BUG] One polygon is not read correctly in `read_polygon_shapefile`

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#612]
**Describe the bug**
When reading the geopandas test Polygon dataset:

```
    host_dataframe = gpd.read_file(
        gpd.datasets.get_path("naturalearth_lowres")
    )
    gs = host_dataframe["geometry"][
        host_dataframe["geometry"].type == "Polygon"]
    ]
    gs.to_file("naturalearth_lowres")
    data = cuspatial.read_polygon_shapefile("naturalearth_lowres")
```
The result of this query produces a list of polygons that from `read_polygon_shapefile` is one polygon shorter than the one produced by GeoPandas. I verified this by re-reading the file after writing the set of polygons back to another shapefile, strictly in GeoPandas.

The difference is in the polygons buffer only:

```
(Pdb) cudf.Series(polygons)[13:18]
13    13
14    14
15    15
16    17
17    18
dtype: int32

```
In the buffer that is parsed directly from the GeoPandas series, there is one extra polygon:
```
(Pdb) cudf.Series(_polygons)[13:18]
13    13
14    14
15    15
16    16
17    17
dtype: int32

```

**Steps/Code to reproduce bug**
The test code to reproduce the bug is here: https://github.com/thomcom/cuspatial/blob/fea-add-read-polygon-shapefile-integration/python/cuspatial/cuspatial/tests/test_geoseries.py#L360-L397

I've included the shapefile directories that are commented out, as well.

**Expected behavior**
The output of the above two sliced `Series` objects should be the same.

**Environment details (please complete the following information):**
`rapids-compose` build, based off of `branch-22.08`

**Comment by thomcom** [comment]
Cutting out that one offending polygon by slicing from [19:] resolved the issue. Apparently there's a spurious Polygon in there that `read_polygon_shapefile` is skipping over?

**Comment by zhangjianting** [comment]
@thomcom as we chatted, can you send the shapefile so that I can reproduce the issue and look into it?

**Comment by zhangjianting** [comment]
manual inspection shows that polygon #15 has two rings, which makes the ring offset column of the next polygon to 17. Sees to be correct.

**Comment by thomcom** [comment]
Thanks @zhangjianting sorry for distracting you. :)
