### ISSUE TITLE
[BUG] Polygons returned from `read_polygon_shapefile` are wound counterclockwise.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#626]
**Describe the bug**
Polygon exteriors from above are wound counter clockwise, and the interiors are clockwise. This is because of 
https://github.com/rapidsai/cuspatial/blob/branch-22.08/cpp/src/io/shp/polygon_shapefile_reader.cpp#L35-L39
This is an easy mistake to make because if you get a sign wrong in any equation in point_in_polygon or any other spatial algorithm, your algorithm will work with polygons of the opposite winding.

Fixing this will break https://github.com/rapidsai/cuspatial/blob/branch-22.08/cpp/src/utility/point_in_polygon.cuh#L48-L59, but fixing it should be easy.

**Steps/Code to reproduce bug**
This bug is hard to identify. I discovered it because of https://github.com/rapidsai/cuspatial/pull/609 which eventually revealed that perfectly read files with `read_polygon_shapefile` were wound opposite of those returned by GeoPandas.

**Expected behavior**
Polygons should have clockwise exteriors and counterclockwise interiors. Any test that fails when this is corrected simply means that the order of difference equations should probably be reversed ie `d = x0 - x1` should become `d = x1 - x0`.

**Comment by harrism** [comment]
FYI comment from @zhangjianting on PR: https://github.com/rapidsai/cuspatial/pull/609#issuecomment-1204575080

**Comment by thomcom** [comment]
Closing this in favor of https://github.com/rapidsai/cuspatial/pull/609 which depends on this.
