### ISSUE TITLE
[DISCUSSION] Standardize API inputs with `GeoSeries`

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#637]
Today the python computation API accepts raw structure of arrays input. Such as:
https://github.com/rapidsai/cuspatial/blob/da1cb97a4df308b9d27566e4c9d9736ca06a9582/python/cuspatial/cuspatial/core/gis.py#L29
and
https://github.com/rapidsai/cuspatial/blob/da1cb97a4df308b9d27566e4c9d9736ca06a9582/python/cuspatial/cuspatial/core/gis.py#L166-L173
The history of this input interface is that cuspatial was used to accelerate specific workflow where developers are very familiar with the underlying data structure of the geometry and used them. General GIS users are not required to know how the data layout before working with GIS functions, and @thomcom and I believe that using `GeoSeries` as the abstraction layer between user and underlying APIs is important.

cuSpatial's GeoSeries API is implemented based on `GeoArrow` specification: https://github.com/geopandas/geo-arrow-spec, under the hood it's an arrow `UnionArray`. This allows `GeoSeries` represent an array of pure or mixed geometry types. Currently many computation API only supports pure geometry array inputs. This falls within the range where `GeoSeries` is capable of supporting.

Ideally, the above APIs should look like:
```python
def directed_hausdorff_distance(points: cuspatial.GeoSeries, space_offset: cudf.Series):
```
```python
def points_in_polygons(points: cuspatial.GeoSeries, polygons: cuspatial.GeoSeries)
```

TODO:

```[tasklist]
### Distance
- [ ] https://github.com/rapidsai/cuspatial/issues/920
- [ ] https://github.com/rapidsai/cuspatial/issues/921
```

```[tasklist]
### Bounding
- [ ] https://github.com/rapidsai/cuspatial/issues/929
- [ ] https://github.com/rapidsai/cuspatial/issues/930
```

```[tasklist]
### Filtering
- [ ] https://github.com/rapidsai/cuspatial/issues/936
```

```[tasklist]
### Indexing
- [ ] https://github.com/rapidsai/cuspatial/issues/937
```

```[tasklist]
### Join
- [ ] https://github.com/rapidsai/cuspatial/issues/939
- [ ] https://github.com/rapidsai/cuspatial/issues/940
- [ ] https://github.com/rapidsai/cuspatial/issues/941
- [ ] https://github.com/rapidsai/cuspatial/issues/942
```

```[tasklist]
### Projection
- [ ] https://github.com/rapidsai/cuspatial/issues/949
```

```[tasklist]
### Trajectory
- [ ] https://github.com/rapidsai/cuspatial/issues/950
- [ ] https://github.com/rapidsai/cuspatial/issues/951
- [ ] https://github.com/rapidsai/cuspatial/issues/952
```

```[tasklist]
### Docs
- [x] Update User Notebook #935
```

**Comment by harrism** [comment]
> Ideally, the above APIs should look like:
>
> `def directed_hausdorff_distance(points: cuspatial.GeoSeries):`

Hmmm, this ignores the spaces in the Hausdorff distance API. This is a directed all-pairs distance computation. So the grouping and order of points matters.

**Comment by harrism** [comment]
I like this direction. API looks much cleaner. As long as we provide factories / converters from other layouts / dataframes.

**Comment by thomcom** [comment]
Thanks for creating this discussion. I agree that we should use `GeoSeries` in any API call that uses coordinates or offsets as much as possible.

**Comment by thomcom** [comment]
I propose that we create individual issues for each API that needs to be updated.

**Comment by harrism** [comment]
let's convert this to a milestone.

**Comment by isVoid** [comment]
> I propose that we create individual issues for each API that needs to be updated.

Went with this way - this issue is now a meta issue that tracks the progress, where each API is tracked with a sub issue in the task list.

**Comment by isVoid** [comment]
This is done.
