### ISSUE TITLE
[FEA] Nearest point and segment index of linestring to a point (pairwise)

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#646]
**Is your feature request related to a problem? Please describe.**

For linestring/point pairs, I would like to calculate not only the distance between points and linestrings, but also the nearest point on the linestring and possibly the index of the segment within the linestring that contains that nearest point.

**Describe the solution you'd like**

Ingestivate leveraging the functionality in #573 to provide the nearest point and segment index.

**Comment by isVoid** [comment]
To clarify, if a point is the same as a vertex, what's the result segment idx?

**Comment by isVoid** [comment]
Another clarification: does this feature include multi-linestring?

**Comment by harrism** [comment]
For the current request I haven't heard that this is needed. However for completeness I guess we should. The question is what do you return if so?

**Comment by isVoid** [comment]
My prototype returns a third column that provides the "part index" of the linestring in a multi-linestring.

**Comment by isVoid** [comment]
A third clarification: in case there are multiple segments having equal distance to the point, how do you break the tie?

**Comment by harrism** [comment]
If we are only returning one, I would suggest to not guarantee any ordering. This gives the most flexibility in a parallel implementation.
