### ISSUE TITLE
[FEA] linestring-linestring intersection (pairwise)

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#648]
**Is your feature request related to a problem? Please describe.**

A function to return, for each specified pair of linestrings, the point at which they intersect. We may also need the segment index within each linestring of the intersection.

https://github.com/rapidsai/cuspatial/issues/648#tasklist-block-d3e21ca2-3c8a-4251-990f-97fe808b41bf

**Comment by isVoid** [comment]
> We may also need the segment index within each linestring of the intersection.

Can you confirm we need it?

**Comment by harrism** [comment]
Based on the recent meeting I believe the answer is yes.

**Comment by isVoid** [comment]
Linestring intersections can return not only points, but also linestrings. This happens when two linestrings overlaps.

**Comment by harrism** [comment]
> point_geometry_idx: list of idx, the `j`th element in the `i`th row of the series indicates the multilinestring idx on lhs/rhs of the `j`th intersecting point of the `ith` pair.
> linestring_geometry_idx: list of idx, the `j`th element in the `i`th row of the series indicates the multilinestring idx on lhs/rhs of the `j`th overlapping linestring of the `ith` pair.
> point_part_idx: list of idx, the `j`th element in the `i`th row of the series indicates the segment idx on lhs/rhs of the `j`th intersecting point of the `ith` pair.
> linestring_part_idx: list of idx, the `j`th element in the `i`th row of the series indicates the segment idx on lhs/rhs of the `j`th overlapping linestring of the `ith` pair.

Oooh, that's confusing...  Perhaps we can encapsulate it somehow.

**Comment by thomcom** [comment]
This is probably why GeoPandas and Shapely just return the objects that are in the intersection, right? We don't want users to have to reconstruct their dataset from indices and etc, maybe we can reorganize the data on the way back to become a new set of union_offsets and union_types that represent the intersection using the original input data?

**Comment by isVoid** [comment]
> using the original input data?

Intersection primitive may create new data that does not belong to original input data. I was thinking of using union column type to encapsulate the intersection point/linestrings. At best it can encapsulate the mixed geometry types. As for client's request on indices that refers back to the original input columns, I haven't come up with a good way to encapsulate it.
