### ISSUE TITLE
[DOC] Performance tuning guide for cuspatial?

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#651]
Currently our kernel launching parameter is arbitrary: most of them pick `64` threads per block. While it makes sense to benchmark every kernel and put the "optimal" TPB in the code, the assumptions made in the benchmark could also go stale in production. It might makes sense to have an extra guide in the documentation laying out the steps we usually follow to benchmark a use case (for both c++ and python). Leave the kernel launch parameter as a template parameter for the header only API and allow user to tune the performance based on different production environments.

**Comment by harrism** [comment]
As we discussed, I think we should choose a reasonable size to start with, and revisit if this becomes a performance problem for someone. Otherwise we are making work for ourselves and optimizing too early.

**Comment by isVoid** [comment]
Closing. Feel free to reopen if necessary.
