### ISSUE TITLE
[FEA] Remove `cartesian_2d` and `lonlat_2d` distinction and use `vec_2d` universally

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#653]
Originally `cartesian_2d` and `lonlat_2d` were introduced to prevent users from applying geometric APIs to geodesic data. So far the only use case of this is `lonlat_to_cartesian_2d`. This proves to be an early optimization.

Moreover, the design of these types are also problematic. The binary operations designed for `vec_2d` are non-applicable to the derived class. Implementing binops for all the derived class will inflate the binops APIs by 2x, and iterator factories in `type_utils.hpp` by 2x.

**Comment by harrism** [comment]
Assigning self. Let's get this done ASAP so it doesn't become a pain to change.
