### ISSUE TITLE
[FEA] Add offset column accessors

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#668]
Our APIs mostly use offset columns passed in as arguments, though @isVoid is making progress to refactoring them to all use `GeoSeries` as input instead. To make development of `GeoSeries` integration easier and to make it much easier to continue to use our algorithms, while also using `GeoSeries` objects, I need to add a `offset_column` accessor to each of the four underlying geometry types stored in `GeoSeries`: `points`, `multipoints`, `lines`, and `polygons`.

I'm currently working on this as

`geoseries.polygons.offset_column(0...3)` in #609. #609 will resolve this.

**Comment by isVoid** [comment]
Interesting, I had a slightly different solution in [660](https://github.com/rapidsai/cuspatial/pull/660)

https://github.com/rapidsai/cuspatial/blob/8cbc55dd26e736338edec6f1bd18339f355feaac/python/cuspatial/cuspatial/core/geoseries.py#L96-L138

**Comment by thomcom** [comment]
Haha indeed! I never used `leaves()` or elements before.

**Comment by thomcom** [comment]
This was closed by #660.
