### ISSUE TITLE
[DOC] Create python guide to writing unit tests

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#694]
We don't have a documentation guide for writing python tests. Using the `cudf` documentation as a starting point, create a python unit test guide.

**Comment by harrism** [comment]
@thomcom @isVoid the latest developer docs include this section on writing tests: https://docs.rapids.ai/api/cuspatial/nightly/developer_guide/contributing_guide.html#writing-tests

Is that sufficient to close this issue or are you planning more?

**Comment by thomcom** [comment]
I'm not planning more at this time it'd be nice to close the issue.

**Comment by harrism** [comment]
We can close the issue *and* the milestone!
