### ISSUE TITLE
[FEA] Simplify Header Based API

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#698]
**Is your feature request related to a problem? Please describe.**
As demontarted in https://github.com/rapidsai/cuspatial/pull/677, the geometry input of the header only API can quickly get out of control for complex geometry. We should try to simplify the APIs to improve developer experience.

**Describe the solution you'd like**
Wrap the iterators in a separate structure as input. Ideally, the new structure should support different parallel model.

Things to convert:

- [ ] linestring distance
- [ ] point linestring ditance
- [ ] point distance
- [ ] point in polygon
- [ ] hausdorff (?)

The new structure should be benchmarked.

**Comment by harrism** [comment]
Should this be a milestone instead of a single issue?

**Comment by isVoid** [comment]
Yes since it takes multiple PRs to finish. Closing in favor of a milestone.
