### ISSUE TITLE
[FEA] Modify `read_polygon_shapefile` to return a `GeoSeries` instead of a tuple.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#715]
**Describe the bug**
`read_polygon_shapefile` returns the basic elements of a `GeoSeries` instead of a `GeoSeries`. To solidify the API, let's have it return the `GeoSeries` itself.

**Comment by harrism** [comment]
What is the C++ equivalent of a `GeoSeries`?

**Comment by thomcom** [comment]
I'm really referring to the python interface in this issue, which was my oversight. There isn't a parallel for `GeoSeries` yet at the C++ level.

In the general case the C++ equivalent is:
A buffer of xy Points
A buffer of xy Points and an offsets buffer of MultiPoint parts
A buffer of xy coordinates, an offsets buffer of LineString start positions and an offsets buffer of MultiLineString parts
A buffer of xy coordinates, an offsets buffer of Polygon rings, an offsets of Polygon start positions, and a buffer of MultiPolygon parts.

`read_polygon_offsets` returns the first three objects in the Polygon set.
