### ISSUE TITLE
[FEA] Automatic batching in point_in_polygon_bitmap computation

### ISSUE THREAD

**Issue by Nanthini10** [rapidsai/cuspatial#72]
**Feature description**
While calling `point_in_polygon_bitmap` with more than 32 polygons, it results in the following error

`RuntimeError: cuDF failure at: /rapids/cuspatial/cpp/src/spatial/point_in_polygon.cu:134: #polygon of polygons can not exceed bitmap capacity (32 for unsigned int)`

**Describe the solution you'd like**
Automatic batching for the polygons would be useful to avoid multiple calls to the function and user-defined batching.

**Describe alternatives you've considered**
Manually batching the polygons and making multiple calls and append the dataframes.

**Additional context**
StackTrace of the error:
```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-b2c41b336501> in <module>
     17     df['LATITUDE'], df['LONGITUDE'],
     18     ids, offsets,
---> 19     lat, lng
     20 )
     21 # bitmaps = cuspatial.point_in_polygon_bitmap(

/conda/envs/rapids/lib/python3.6/site-packages/cuspatial-0.10.0a0+144.g5e188f1-py3.6-linux-x86_64.egg/cuspatial/core/gis.py in point_in_polygon_bitmap(x_points, y_points, polygon_ids, polygon_end_indices, polygons_x, polygons_y)
    133         polygon_end_indices,
    134         polygons_x,
--> 135         polygons_y,
    136     )
    137 

cuspatial/_lib/spatial.pyx in cuspatial._lib.spatial.cpp_point_in_polygon_bitmap()

cuspatial/_lib/spatial.pyx in cuspatial._lib.spatial.cpp_point_in_polygon_bitmap()

RuntimeError: cuDF failure at: /rapids/cuspatial/cpp/src/spatial/point_in_polygon.cu:134: #polygon of polygons can not exceed bitmap capacity (32 for unsigned int)
```

**Comment by linwoodc3** [comment]
Same happened to me today.

**Comment by zhangjianting** [comment]
We will be working on two solutions: 
1) If one point can only fall within a single polygon, a polygon ID, instead of a bitmap, will be returned. This will allow 2^32 polygons. 
2) if any point can fall within any polygon, a sparse array representation, e.g., CSR, is necessary. This will require significant change to the GPU kernel and users are responsible to handle sparse array representation.   
Can you please let me know which solution suits your application better? 
Thanks --Jianting Zhang

**Comment by thomcom** [comment]
We've renamed the `point_in_polygon_bitmap` function to simply `point_in_polygon`. Now it uses a quad tree to identify candidate polygons and works with more than 31 polygons. Take another look when you have the chance!
We're updating our notebook at https://github.com/rapidsai/cuspatial/blob/branch-0.18/notebooks/nyc_taxi_years_correlation.ipynb to demonstrate how to use the new API.
