### ISSUE TITLE
[FEA] Implement binary predicates that depend only on point-in-polygon

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#722]
**Is your feature request related to a problem? Please describe.**
Some spatial predicates depend only on the outcome of point-in-polygon.

**Describe the solution you'd like**
I can work on these predicates in python while the `equals` and `intersects` basic predicates are being worked on.

Equality/Intersection/PIP table
Legend:
x: False/impossible
e: uses equality
i: uses intersection
p: uses pip

  | x(p, p) | x(p, l) | x(p, P) | x(l, p) | x(l, l) | x(l, P) | x(P, p) | x(P, l) | x(P, P)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Equals | e | x | x | x | e | e | e | e | e
Disjoint | e | e | e | i | i | ip | ep | ep | ep
Touches | e | e | p | i | i | ip | ip | ip | ip
Contains | e | x | x | i | e | x | p | p | p
Covers | e | x | x | i | e | x | ip | ip | ip
Intersects | e | e | p | i | i | i | ip | ip | ip
Within | e | e | p | x | e | p | x | x | p
CoveredBy | e | e | p | x | e | p | x | x | p
Crosses | e | x | x | i | i | i | i | i | i
Overlaps | e | x | x | i | i | i | p | i | i

https://github.com/rapidsai/cuspatial/issues/722#tasklist-block-68684f15-c10b-4537-8c90-e2423e25a899

**Comment by harrism** [comment]
@thomcom please add a tasklist and use this issue as an epic.

**Comment by thomcom** [comment]
I implemented them all yesterday morning. They are implemented insofar as only point-in-polygon, with the exception of boundary testing, is required.

**Comment by harrism** [comment]
Goal of task lists is for each task to become an issue to give one place.to track an epic. If these are all done in one go, probably didn't need a task list. :)

**Comment by thomcom** [comment]
It was shorter and easier than I expected - I didn't end up making any separate issues out of it, just writing them up and testing them as I went. I'm working on a refactor that will close this issue hopefully soon.
