### ISSUE TITLE
[FEA] Determine if point-in-polygon is exterior inclusive or not.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#738]
**Is your feature request related to a problem? Please describe.**
https://docs.geopandas.org/en/latest/docs/reference/api/geopandas.GeoSeries.contains.html#geopandas.GeoSeries.contains specifies that `.contains` is exterior-exclusive. That is, the boundary of a Polygon is defined to not be contained within the polygon. 

**Describe the solution you'd like**
In order to implement `.contains`, I need to verify if our implementations of point-in-polygon follow this same rule. I'll write a test that validates if a point that matches the point of a Polygon is in-polygon. I'll write another test to see if a point that is collinear to two points in the Polygon is in-polygon. If not, great!

**Comment by thomcom** [comment]
The result of the test is that the basic pip algorithm is border-exclusive for points in the border, but it is border-inclusive for points that are collinear with points in the border. This contrasts GeoPandas which is border-exclusive for both cases.

**Comment by harrism** [comment]
If it was entirely border-inclusive (including vertices) I would wonder if this is intentional. But the fact that border points are exclusive and border edges are inclusive seems inconsistent, and therefore I lean toward this being a bug.
