### ISSUE TITLE
[FEA] Write .contains_properly for points, multipoints, linestrings, and polygons.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#743]
.contains is the most point-in-polygon-like binary operation.

For points, the result is the same as our point_in_polygon methods. I'll need to disambiguate between requests with 31 rows or fewer. In the case of 31 rows, use the unindexed point_in_polygon, or with more rows use quadtree. After the call is complete, the diagonal of the resulting DataFrame will need to be copied into a new Series.

For multipoints, linestrings, and polygons the behavior is the same as above, with an additional step to compute which complex geometry each point is a member of.

This will probably require building a new indexing scheme that allows any `xy` pair pulled from the coordinates buffer to be referenced back to its originating feature.

Write tests that slowly explore each of the above cases, comparing with GeoPandas results. If I'm lucky, our results will mostly match GeoPandas and all of .contains can be written in the next couple of weeks.

**Comment by thomcom** [comment]
I've spent a lot of time this week trying to add a colinearity test to our point_in_polygon kernel, so that it will exclude the boundary. It has improved the results, but I'm stumped on a case where colinearity should exclude the point but is not. I don't want to dig on this forever, so I may start working on the rest of `.contains` even though I know the results aren't perfectly correct.

**Comment by harrism** [comment]
Can you share / document the case that is stumping you?
