### ISSUE TITLE
[FEA] Define coordinate systems used in lonlat_to_xy_km_coordinates

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#75]
lonlat_to_xy_km_coordinates doesn't define its transformation exactly. It is just the haversine equation? We should document this.

Similarly, we may want to enable the definition of different coordinate systems when using this function. @zhangjianting what do you think?

**Comment by ChrisMLroy** [comment]
Seconded--this will be very useful for specific coordinate systems (NVIDIA's RAPIDS Fundamentals DLI uses a conversion from WGS84 lat/long to OSGB36 grid coordinates), and it would be helpful to have clarity on what assumptions are being made in this transform.

**Comment by zhangjianting** [comment]
Sorry that I missed @thomcom  comment.  This function was a CUDA port of a Java function for Intelligent Transportation applications using surveillance cameras. I do not fully understand the algorithm behind but it could be an approximation of  Haversine distance relative to a camera location in lat/lon. 
@thomcom  did you have a chance to talk with John Murray and see how he would like to contribute to projection? Do you want to take a lead on porting John Murray's Numba code in cuSpatial to speed up the support for geographical projections?

**Comment by ChrisMLroy** [comment]
Prompted by the github-actions bot: cuSpatial can definitely still benefit from coordinate system awareness and transforms. We should at least be documenting some bounds on this method's applicability--it's assuming some projection and approximate Cartesian flatness within that projection.
