### ISSUE TITLE
[FEA] GeoSeries needs index alignment

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#761]
**Is your feature request related to a problem? Please describe.**
GeoPandas implements pairwise comparisons in their binary operations. The default argument for all binary operations is `align=True` which index-aligns the GeoSeries before calling the binary operation. We need to support at least at a default argument level the align call so that we can match their default behavior.

See https://github.com/rapidsai/cuspatial/issues/761#issuecomment-1299170908 for more details.

**Describe the solution you'd like**
Handle index alignment when `.contains_properly` is called.

**Describe alternatives you've considered**
Don't support index alignment.

**Comment by thomcom** [comment]
For our implementation, index alignment means that two `GeoSeries` with different indexes are aligned by reordering so that they can be compared by index. Specifically for `GeoPandas` I need to be able to compare two `GeoSeries` of different lengths $m > n$, then create a new `GeoSeries` containing $m-n$ `None` values, sorted by index. 
```
>>> polygons = gpd.GeoSeries([
        Polygon(((-8, -8), (-8, 8), (8, 8), (8, -8))),
        Polygon(((-2, -2), (-2, 2), (2, 2), (2, -2))),
    ])
>>> polygon = gpd.GeoSeries(polygons[0]) 
>>> polygon.align(polygons)
(0    POLYGON ((-8.00000 -8.00000, -8.00000 8.00000,...
 1                                                 None
 dtype: geometry,
 0    POLYGON ((-8.00000 -8.00000, -8.00000 8.00000,...
 1    POLYGON ((-2.00000 -2.00000, -2.00000 2.00000,...
 dtype: geometry)
 ```

**Comment by harrism** [comment]
Add this to the description. :)
