### ISSUE TITLE
[FEA] new IO module for ESRI Shapefile

### ISSUE THREAD

**Issue by zhangjianting** [rapidsai/cuspatial#77]
**Is your feature request related to a problem? Please describe.**
Currently cuSpatial supports reading polygon data from disk files in SoA (Structure of Arrays) format. A standalone tool under "data" was developed to convert ESRI shapefiles to SoA files. Instead of following the two-step approach, an integrated approach that reads ESRI shapefiles from disks to gdf columns is desirable and has been requested by several customers.  

**Describe the solution you'd like**
Refine data/poly2soa.cpp code to make it a c++ API and  subsequently develop a Python wrapper API for it.

**Comment by thomcom** [comment]
I'm getting started on the python wrapper for this.

**Comment by zhangjianting** [comment]
Thanks.

**Comment by harrism** [comment]
I think this was fixed when we added https://docs.rapids.ai/api/cuspatial/nightly/api_docs/io.html#cuspatial.read_polygon_shapefile

Closing.
