### ISSUE TITLE
Remove duplicates in linestring intersection results

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cuspatial#792]
As a post processing step in intersection, we should remove duplicates in points set, and segments set. Looking at the number of points, we should also determine if the points and the segments can merge.

https://github.com/rapidsai/cuspatial/issues/792#tasklist-block-d1e15ab1-aa84-43e9-b0e4-c481f83829bb

**Comment by jarmak-nv** [comment]
Hey @isVoid it looks like this is complete based on the tasks and the issue tracking it, but not 100% sure. If done, please close it, thanks!
