### ISSUE TITLE
Refactor contains from `geoseries.py` into `core/binops/contains.py`

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#827]
Refactor contains from `geoseries.py` into `core/binops/contains.py`. This will contribute to designing the factoring of the abstraction for binops. I don't want `GeoSeries.py` to be cluttered with binops code, it should live in its own directory.

_Originally posted by @thomcom in https://github.com/rapidsai/cuspatial/pull/749#discussion_r1035119840_

**Comment by harrism** [comment]
Perhaps a more concise issue title? :)
