### ISSUE TITLE
[FEA]: `point_in_polygon` doesn't use `GeoArrow` style offsets

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#829]
Closed by #973

### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

`point_in_polygon` was written before `GeoArrow`. It's offset buffers are only length `n` for a Feature with `n` geometries, but `GeoArrow` has the tail `n+1` offset. We need to update `point_in_polygon` to match `GeoArrow.`

**Comment by harrism** [comment]
I would say this is true of all of our existing polygon APIs. e.g. polygon_bounding_boxes.  Remind me again why Arrow needs n+1 storage for n items?

**Comment by thomcom** [comment]
It stores the final "end position", instead of letting the user assume that it is "length of data buffer offsets refer to minus the size of the final offset". This makes it so that special logic is not required for the end segment when iterating, but that's as much as I can guess why.

**Comment by thomcom** [comment]
This is closed by #973
