### ISSUE TITLE
[FEA]: Binary predicates that depend only on equals

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#838]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Many binary operations depend only on tests for equality. This issue is an epic for planning, tracking, and completing the binary operations depending only on equality.

Implement the binary operations that depend on equality. These operations include:
### Strict equality: `len(lhs) == len(rhs) && count_equals(lhs, rhs) == len(rhs)`
1. point equals point
3. linestring equals linestring
4. linestring equals polygon
7. polygon equals linestring
- What about closed vs. unclosed polygons?
8. polygon equals polygon
13. point contains point
15. point covers point
17. point intersects point
19. point within point
22. point coveredby point
25. point crosses point
26. point overlaps point

### Weak equality: `len(lhs) > len(rhs) && count_equals(lhs, rhs) == len(rhs)`
6. polygon equals point
14. linestring contains linestring
17. linestring covers linestring
18. point intersects linestring
20. point within linestring
21. linestring within linestring

### Strict inequality: `count_equals(lhs, rhs) == 0`
10. point disjoint point
11. point disjoint linestring
12. point disjoint polygon

Each of this binops depends on particular counting operations to occur as postprocessing. This issue also tracks those operations.

<b style="font-weight:normal;" id="docs-internal-guid-da5a398c-7fff-f004-66cb-6989e0b380d7"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Equality/Intersection/PIP table</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Legend:</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">x: False/impossible</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">e: uses equality</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">i: uses intersection</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">p: uses pip</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

  | x(p, p) | x(p, l) | x(p, P) | x(l, p) | x(l, l) | x(l, P) | x(P, p) | x(P, l) | x(P, P)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Equals | e | x | x | x | e | e | e | e | e
Disjoint | e | e | e | i | i | ip | ep | ep | ep
Touches | ei | ei | ip | ei | ei | ip | ip | ip | ip
Contains | e | x | x | i | e | x | p | p | p
Covers | e | x | x | i | e | x | ip | ip | ip
Intersects | e | i | p | i | i | i | ip | ip | ip
Within | e | e | p | x | e | p | x | x | p
CoveredBy | e | e | p | x | e | p | x | x | x
Crosses | e | x | x | i | i | i | x | ip | ip
Overlaps | e | x | x | i | i | i | p | ip | ip

</div></b>

**Comment by harrism** [comment]
When you say count_equals between two sets of points, what exactly do you mean? What if there is a polygon

```
P0 -- P1
|      |
P3 -- P2
```

And a linestring
```
P3 -- P2
|      |
P0 -- P1
```

They have all the same points, but in different order. Do you have to do all-pairs equality tests between the point sets and count the number of equal points? That sounds similar to our Hausdorff implementation.

**Comment by thomcom** [comment]
Presently I only treat P0->P1->P2->P3 as equals, the other is not considered equal. If we determine that the latter case is more appropriate than the former, I think I can handle equals still by sorting the points before checking for equality without doing an all-pairs equality test.

**Comment by harrism** [comment]
And really I think what you want is all_equal, not count_equal.
