### ISSUE TITLE
[FEA]: Implement and benchmark quadtree point-in-polygon for binops.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#844]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Because point in polygon is limited to 31 polygons, all binary operations that depend on point-in-polygon are also limited to 31 polygons. The best solution for this is to switch the pip algorithm from "brute force" to quadtree. I need to replace the point-in-polygon binary operation with a quadtree based implementation and modify the outputs to utilize the alternative output that the quadtree approach creates.

### Describe any alternatives you have considered

I also considered using the unlimited polygons pip that @isVoid and I implemented, but it is limited by the 2^32 row limit of cudf columns.

**Comment by harrism** [comment]
> I also considered using the unlimited polygons pip that @isVoid and I implemented, but it is limited by the 2^32 row limit of cudf columns.

Only the column-based API has that limit. All cuDF column-based APIs have that limit, including the quadtree-based PiP.

I think we need more elaboration comparing what combinations of comparisons are really needed versus what our various C++ implementations provide today. I really think that the complexity of spatial queries is getting to the point where we need a detailed design document. An additional benefit is that then the design is not just in one person's head.

**Comment by thomcom** [comment]
I've created a benchmark summary doc here which I intend to iterate.
https://docs.google.com/document/d/1J9UFyvxw1xOVNUEOAED7d1igX6gHCjB-nY7sSf1RllM/edit?pli=1#heading=h.8gudvpfd7tq6

**Comment by harrism** [comment]
No benchmark code checked in?
