### ISSUE TITLE
[FEA]:  Use pip to install cuspatial

### ISSUE THREAD

**Issue by scalemailted** [rapidsai/cuspatial#869]
### What is your question?

Given that Google Colaboratory now supports python3.8 and some of the other rapidai packages now support pip installation, is it possible to use pip to install cuspatial into a Google Colab notebook?

**Comment by thomcom** [comment]
Thanks for your request @scalemailted ! The answer to your question is that we are working on it and it should be coming up soon.

**Comment by scalemailted** [comment]
Thank you so much for both responses. I am so impressed by the responsiveness of this team! It appears that my question was elevated into a feature request and picked up into a sprint within just days of my asking.

**Comment by harrism** [comment]
In this case your question happens to be aligned with existing requests / plans. The rest of RAPIDS is already moving to support PIP, so we want to do so for cuSpatial as well.

**Comment by jarmak-nv** [comment]
Hi @scalemailted - just wanted to update you that due to some competing priorities we had to push this back to 23.06 - for 23.04 conda, docker, and building from source will remain the installation methods for cuSpatial.
