### ISSUE TITLE
[FEA]: Deprecate GDAL-based shapefile reader 

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#870]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Our shapefile reader is written in C++ using GDAL. The GDAL dependency makes it difficult to add pip install support for cuSpatial, which is a priority. Also, the shapefile reader is limited in functionality -- for example it does not support multipolygons. 

Users will still be able to use other Python libraries to load shapefiles. We should make sure the data loaded from shapefiles is still easy to get into cuSpatial, but we do not think we need C++-level support.

### Additional context

We should aim to deprecate this functionality in 23.02 and remove it in 23.04.

**Comment by zhangjianting** [comment]
+1
The C++ shapefile reader was developeed before Python APIs were developed. Transfering geometry data to GPU through Python APIs is preferable, unless the geometry data has very large volumes which may cause performance concerns. Polylines/polygon data typically are small in volumes comparing to point data.

**Comment by harrism** [comment]
Renamed this to deprecate, which is done. Opened #931 to cover removal.
