### ISSUE TITLE
[DOC]: Create new notebook for demoing cuSpatial at GTC

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#883]
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

I'm creating a notebook from former cuSpatial workflows and trying to develop something new and interesting using our Binary Predicates (namely `.contains_properly`) and our distance functions.

Currently I'm loading the taxi pickups and dropoffs data and working on interesting analysis with this data. This is rehashing old efforts, but the data is well understood and fairly large in scale. The easiest analysis is to count the number of pickups and dropoffs per zone, but this has already been done, though not with `.contains_properly`.

I'm finding the runtime of `.contains_properly` to be slow, about 500ms per polygon, which is 4x faster than GeoPandas on the same data. A good place to create an issue.

I have the national address database (NAD) loaded into the notebook as well and am taking only the NY addresses. These addresses can be compared with the boroughs or pickup/dropoff locations to attach a street name to each location, or to identify all the streets or addresses that are within each borough. This is novel work and promising, though our distance function is pairwise and it could be an expensive run. Tomorrow I'll try to run this.

Finally an obvious analytic is to compute the number of addresses in the NAD per Taxi zone. This is also a novel use case but follows the same pattern as the taxi pickups and dropoffs and should be pretty straight forward.

Finally I'm uncovering a number of bugs, possibly 23.04 regressions, and am working through those as I progress. I haven't filed any issues for them given the short timeline we have on getting slides and presentation material ready for GTC but I am taking detailed notes and will put things together when I feel less time pressure.

**Comment by thomcom** [comment]
The new notebook is https://github.com/thomcom/gtc-2023

**Comment by harrism** [comment]
Please move it to a RAPIDS repository.

**Comment by jarmak-nv** [comment]
reopen to get into cuspatial instead of your personal repo
