### ISSUE TITLE
[BUG]: Inconsistent values produced by directed_hausdorff_distance across different versions of cuspatial

### ISSUE THREAD

**Issue by abhilshitsoni-tomtom** [rapidsai/cuspatial#885]
### Version

22.02

### On which installation method(s) does this occur?

Docker

### Describe the issue

I am having 2 parallel setups to test cuSpatial on my databricks runtime that uses docker container 

1. The first one uses docker container built using https://github.com/databricks/containers/tree/master/ubuntu/gpu/cuda-11/rapids (image officially published on dockerhub as databricksruntime/gpu-rapids:cuda11 ) this uses rapids 22.02 with cuda11.2 and is deployed on databricks with following settings 

Databricks Runtime:  9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)
Worker Type : Standard NC6_v3 (uses NVIDIA Tesla V100 GPU)
Driver Type : Standard NC6_v3  (uses NVIDIA Tesla V100 GPU)
Docker Image URL:  databricksruntime/gpu-rapids:cuda11

2. The second setup uses docker container built using https://github.com/databricks/containers/tree/master/ubuntu/gpu/cuda-10.1/rapids (image officially published on dockerhub as databricksruntime/gpu-rapids:cuda10.1 ) this uses rapids 0.13 with cuda 10.1 and is deployed on databricks with following settings 

Databricks Runtime:  7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)
Worker Type : Standard NC6_v3 (uses NVIDIA Tesla V100 GPU)
Driver Type : Standard NC6_v3  (uses NVIDIA Tesla V100 GPU)
Docker Image URL:  databricksruntime/gpu-rapids:cuda10.1

My usecase is similar to trajectory clustering where I need to calculate a pairwise directed_hausdorff_distance matrix to be provided to DBSCAN. However, both systems are giving inconsistent results of distance matrix on same data. On inspecting further I tried to run the directed_hausdorff_distance example code for both the versions taken from here 

https://github.com/rapidsai/cuspatial/blob/branch-22.02/python/cuspatial/demos/hausdorff_clustering_test_toy.py
Here is the code snippet followed by its output on both the setups

```
import numpy as np
from sklearn.cluster import DBSCAN, AgglomerativeClustering

from cudf import Series

import cuspatial

in_trajs = []
in_trajs.append(np.array([[1, 0], [2, 1], [3, 2], [5, 3], [7, 1]]))
in_trajs.append(np.array([[0, 3], [2, 5], [3, 6], [6, 5]]))
in_trajs.append(np.array([[1, 4], [3, 7], [6, 4]]))
out_trajs = np.concatenate([np.asarray(traj) for traj in in_trajs], 0)
py_x = np.array(out_trajs[:, 0])
py_y = np.array(out_trajs[:, 1])
py_cnt = []
for traj in in_trajs:
    py_cnt.append(len(traj))
pnt_x = Series(py_x)
pnt_y = Series(py_y)
cnt = Series(py_cnt)
distance = cuspatial.directed_hausdorff_distance(pnt_x, pnt_y, cnt)
print(distance)
```

**Running the above code on setup # 1 produces following results**

```
               0              1    2
0  -1.000000e+00  -1.000000e+00 -1.0
1  -1.000000e+00  -1.000000e+00 -1.0
2  1.340781e+154  1.340781e+154  0.0

```
**While same code on setup# 2 produces following results**

```
          0         1         2
0  0.000000  4.123106  4.000000
1  3.605551  0.000000  1.414214
2  4.472136  1.414214  0.000000

```
The output of setup#1 is totally incorrect. I could manually calculate and verify that output of setup#2 is correct. Not sure why there is this inconsistency, but this prevents us from using newer versions of cuSpatial with newer spark versions.

### Minimum reproducible example

```shell
`import numpy as np
from sklearn.cluster import DBSCAN, AgglomerativeClustering

from cudf import Series

import cuspatial

in_trajs = []
in_trajs.append(np.array([[1, 0], [2, 1], [3, 2], [5, 3], [7, 1]]))
in_trajs.append(np.array([[0, 3], [2, 5], [3, 6], [6, 5]]))
in_trajs.append(np.array([[1, 4], [3, 7], [6, 4]]))
out_trajs = np.concatenate([np.asarray(traj) for traj in in_trajs], 0)
py_x = np.array(out_trajs[:, 0])
py_y = np.array(out_trajs[:, 1])
py_cnt = []
for traj in in_trajs:
    py_cnt.append(len(traj))
pnt_x = Series(py_x)
pnt_y = Series(py_y)
cnt = Series(py_cnt)
distance = cuspatial.directed_hausdorff_distance(pnt_x, pnt_y, cnt)
print(distance)
`
```

### Relevant log output

```shell
**Running the above code on setup # 1 produces following results**

               0              1    2
0  -1.000000e+00  -1.000000e+00 -1.0
1  -1.000000e+00  -1.000000e+00 -1.0
2  1.340781e+154  1.340781e+154  0.0

**While same code on setup# 2 produces following results**

          0         1         2
0  0.000000  4.123106  4.000000
1  3.605551  0.000000  1.414214
2  4.472136  1.414214  0.000000
```

### Environment details

```shell
Environment Details : Azure Databricks with setups as mentioned in the issue description
```

**Comment by thomcom** [comment]
I confirmed this result using the latest build off of 23.04 and rapids-compose. I agree there's a regression with the latest version of `directed_hausdorff_distance` we'll have to investigate.

**Comment by abhilshitsoni-tomtom** [comment]
thank you, this works :)

**Comment by abhilshitsoni-tomtom** [comment]
May be, updating the example code in the respective branches can avoid this being reported again.

**Comment by harrism** [comment]
We have open issues to replace everything in the `demos` folder. I think that should suffice.  #209 #312 #341
