### ISSUE TITLE
[QST]: API namespace design question due to duplicated functions at different locations.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#903]
### What is your question?

While @taureandyernv was debugging the unit test failures for `users.ipynb` he was puzzled as to whether `cuspatial.pairwise_linestring_distance` and `cuspatial.core.spatial.distance.pairwise_linestring_distance` were the same function.

I'm pretty sure they are. My question is, do we want to continue exposing function names on the root namespace so that they are simple to type in? Is it even possible to hide the more specific function name from users (not iirc) if we want to then attach it as a member of the primary namespace?

@isVoid @harrism

**Comment by isVoid** [comment]
> My question is, do we want to continue exposing function names on the root namespace so that they are simple to type in?

I vote for no. This bugged me for a long time. It creates a lot of issue such as circular import and messes up the layered architecture.

**Comment by thomcom** [comment]
I'm fine with that. It'll be a substantial refactor though as the notebooks, docs, and tests will all need to be updated.

**Comment by jarmak-nv** [comment]
Closing: Will create a feature req to refactor.
