### ISSUE TITLE
Create Geometry Objects? [QST]

### ISSUE THREAD

**Issue by achapkowski** [rapidsai/cuspatial#91]
**What is your question?**
I see you feed in numpy array, but since a shapely object or arcgis object is the most common geometry object, would it be better to feed in the object type into a column and convert it on the fly?

**Comment by zhangjianting** [comment]
Thanks for the suggestion. We are developing a shapefile reader for polygons(which can also be applied to polylines) and the PR is under review. 
https://github.com/rapidsai/cuspatial/pull/86.

**Comment by zhangjianting** [comment]
Andrew: do you think you can take the lead on this? We are under very strict resource constraints and community contributions are extremely welcomed. --Jianting

**Comment by zhangjianting** [comment]
@thomcom @achapkowski I took at quick look at Fiona. I think the framework underneath can be used to convert cudf columns into python objects to get cuSpatial results back to third-party Python applications for additional processing. We need data flows both in and out of Python objects to interoperate with existing Python geospatial packages (at least for now).

**Comment by harrism** [comment]
Closing as this issue predates our shapefile support and GeoArrow support and other geometry I/O is covered by #165.
