### ISSUE TITLE
cuSpatial: CUDA 12 Conda Packages

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cuspatial#925]
Pushing for CUDA 12 Conda package builds of libraries for RAPIDS 23.04. This issue is for tracking that work.

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Toolkit dependencies from Conda
- [ ] https://github.com/conda-forge/staged-recipes/pull/21723
- [ ] https://github.com/conda-forge/staged-recipes/pull/21350
- [ ] https://github.com/conda-forge/staged-recipes/pull/22355
```

```[tasklist]
### RAPIDS Conda dependencies
- [ ] https://github.com/rapidsai/rmm/issues/1207
- [ ] https://github.com/rapidsai/cudf/issues/12771
```

```[tasklist]
### Other dependencies from Conda using CUDA
- [ ] https://github.com/conda-forge/numba-feedstock/issues/112
```

**Comment by harrism** [comment]
Do other RAPIDS libraries need to be in this list, e.g. RMM and cuDF?

**Comment by jakirkham** [comment]
They could be added to "Other dependencies from Conda using CUDA". Though that's not needed

Mostly trying to capture anything outside of RAPIDS (like CUDA Toolkit dependencies or conda-forge dependencies) that may be needed

**Comment by jarmak-nv** [comment]
Per a message from @trxcllnt and the above comments, I updated the toolkit dependencies to just `libcusparse` and added `libcudf` to the other dependencies

**Comment by jarmak-nv** [comment]
We'll be removing our `libcusparse` dependency in 23.04

**Comment by harrism** [comment]
libcusparse dependency removed in #959.

**Comment by harrism** [comment]
Added Numba and CUDART.

**Comment by harrism** [comment]
> I've confirmed the list below is correct (or updated if not)

Who is "I" in this case? Kind of a weird checklist item...

**Comment by jakirkham** [comment]
Thanks Mark! 🙏

> libcusparse dependency removed in #959.

Deleted that item

> Added Numba and CUDART.

Have converted these into (issue & PR) links

> > I've confirmed the list below is correct (or updated if not)
> 
> Who is "I" in this case? Kind of a weird checklist item...

Developers of the library. Since I'm writing these as an outsider of the development process, am trying to confirm that things are correct from your perspective (or correct them if not)

In any event am learning that the structure of these lists was not entirely clear to folks and could have been improved. Feedback on specific improvements would be welcome :)

**Comment by jakirkham** [comment]
Current work using `nvidia` channel packages in PR ( https://github.com/rapidsai/cuspatial/pull/1044 )
