### ISSUE TITLE
[FEA]: Test notebooks in CI

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#954]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

We should test running our notebooks in CI. We have had situations where API changes have broken our notebooks. This would prevent that (at least for API syntax changes).

### Additional context

Fixed by #953

**Comment by thomcom** [comment]
@taureandyernv has CI for notebooks set up in some other CI environment. I'm not sure if it is possible to run the notebooks CI as a part of our normal pass/fail process, ideas @taureandyernv ?
