### ISSUE TITLE
[FEA]: Write tests for `multipolygon_{range/ref}`, `polygon_{range/ref}`, `linestring_{range/ref}`, etc.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#991]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

I love the new C++ object references you've designed to be used with thrust @isVoid, they seem like they'll really improve development of libcuspatial.

Because they are such fundamental elements of the libcuspatial API, I think that you should write unit tests for them that exercise the functionalities they are expected to have.

**Comment by isVoid** [comment]
100%. Because the infrastructure used in all st_distance APIs, they are "semi-tested" in the integration tests with distance tests. But unit testing would definitely make developer's life easier.
